# -*- coding: utf-8 -*-
"""近邻库种子·B 批：此前散在各条审计记录里、但从未结构化入索引的占位者。

来源线索：知识论 ch26 占位审计 / 特征律线 / 回写缺失 / 操作自盲 / 后果回路 / 引擎室十四位。
"""

CARDS_B = [
 # ── 知识论 ch26 占位审计 ────────────────────────────────────
 dict(id="nbr-0101", ring="知识论",
  prop="知识概念的功能是标识好的信息提供者；它从探询者需要辨认谁可信这一实践需求中长出来",
  alias=["知识的谱系", "好的信息提供者", "探询者的需求", "knowledge as a state of nature 概念的实践起源"],
  src=dict(author="Edward Craig", title="Knowledge and the State of Nature", year=1990),
  holds="任何「知识不是先在的对象、而是从某种实践需求中被结算出来」的判断",
  sep=["克雷格的起点是识别可信者这一社会协调需求，产物是一个概念（knowledge 这个词的功能）",
       "若候选主张的是知识作为过程本身的再发生条件（不是概念的谱系而是知识事件的生成条件），才有剩余"],
  verify="verified", frm="知识论 ch26 占位审计"),

 dict(id="nbr-0102", ring="知识论",
  prop="知识不是对既成实在的表象，而是探究这一活动在解决不确定情境时的产物",
  alias=["探究理论", "inquiry", "有保证的可断言性", "知识是做出来的不是照出来的", "情境的不确定性驱动探究"],
  src=dict(author="John Dewey", title="Logic: The Theory of Inquiry", year=1938),
  holds="任何「知识是过程的产物而非起点的圣物」的判断",
  sep=["杜威的探究以问题情境的解决为终点，产物是有保证的可断言性，重心在方法与实验",
       "若候选主张知识在被结算出来的同时也被消耗/死亡（有生有灭的代谢结构），才有剩余"],
  verify="verified", frm="知识论 ch26 占位审计"),

 dict(id="nbr-0103", ring="科学知识社会学",
  prop="要判断实验做得对不对，得先知道正确结果是什么；要知道正确结果，又得先有做得对的实验——回归无出口，实际由社会协商终止",
  alias=["实验者回归", "experimenter's regress", "判据循环", "谁来裁定裁定者",
         "争议由共同体协商而非数据终结"],
  src=dict(author="Harry Collins", title="Changing Order", year=1985),
  holds="任何「验证的判据本身需要被验证」的判断",
  sep=["柯林斯的回归在争议期出现、由共同体的社会协商关闭；重心是争议的社会学",
       "若候选主张的是常规期（无争议时）该循环仍在运转且不可见，才有剩余"],
  verify="verified", frm="知识论 ch26 占位审计"),

 dict(id="nbr-0104", ring="科学技术论",
  prop="事实不是被发现的，是在实验室里被一整套铭写装置制造出来并逐步剥去制造痕迹的",
  alias=["实验室生活", "铭写装置", "事实的建构", "黑箱化", "痕迹被抹去后事实显得自然而然"],
  src=dict(author="Bruno Latour & Steve Woolgar", title="Laboratory Life", year=1979),
  holds="任何「产物成立之后其产道被抹去」的判断",
  sep=["拉图尔的黑箱化重心在网络的稳定与盟友的招募",
       "若候选主张产道与产物可分离、且分离本身有独立后果（担保体系可以猝死而对象仍在），才有剩余"],
  verify="verified", frm="知识论 ch26 占位审计"),

 dict(id="nbr-0105", ring="科学技术论",
  prop="不同学科有各自的认知机器与知识生产文化，不存在统一的科学方法",
  alias=["认知文化", "epistemic cultures", "各学科自有其认知机器", "知识生产的机器差异"],
  src=dict(author="Karin Knorr-Cetina", title="Epistemic Cultures", year=1999),
  holds="任何「知识生产装置随学科而异」的判断",
  sep=["她的对象是学科间的横向差异；若候选处理的是同一装置内的纵向发生（一个认知对象如何诞生与死亡），才有剩余"],
  verify="verified", frm="知识论 ch26 占位审计"),

 dict(id="nbr-0106", ring="管理学",
  prop="知识在默会与明言之间循环转换（社会化—外化—组合—内化），组织由此创造新知识",
  alias=["SECI 模型", "知识创造", "默会转明言", "知识螺旋", "知识创造型企业"],
  src=dict(author="Ikujiro Nonaka", title="The Knowledge-Creating Company", year=1995),
  holds="任何「知识在组织内被生产而非被传递」的判断",
  sep=["野中的循环以知识为可转换的存量，四种模式各有明确操作；重心在管理可干预性",
       "若候选主张知识的发生有不可被这四格覆盖的一环（例如结算之后的死亡、或代谢裂缝），才有剩余"],
  verify="verified", frm="知识论 ch26 占位审计"),

 dict(id="nbr-0107", ring="技术哲学",
  prop="人的记忆与技能持续外化到器具中；技术是人的第三持存，人与技术互相构成",
  alias=["外化", "第三持存", "技术与时间", "器具承载记忆", "人在外化中成为人"],
  src=dict(author="André Leroi-Gourhan / Bernard Stiegler", title="Le Geste et la Parole / La technique et le temps", year=1964),
  holds="任何「能力被外化到装置之后人这一侧发生了什么」的判断",
  sep=["这一支的判断是互相构成、原则上不做损失判定（外化即人之为人）",
       "若候选主张某一次外化越过临界后产生不可逆的能力坏死，须直面『外化一直在发生、凭什么这次是损伤』这一反驳"],
  verify="verified", frm="知识论 ch26 占位审计"),

 dict(id="nbr-0108", ring="技术哲学",
  prop="个体不是既成的，个体化是一个持续进行、永不穷尽的过程；技术物同样有其个体化的存在方式",
  alias=["个体化", "individuation", "前个体", "技术物的存在方式", "个体是过程不是实体"],
  src=dict(author="Gilbert Simondon", title="Du mode d'existence des objets techniques", year=1958),
  holds="任何「个体/对象是被生成的而非既成的」的判断",
  sep=["西蒙东的个体化是本体论层的普遍过程，无所谓成败",
       "若候选要指认某一次个体化被截断或被代理接管，须给出这次截断相对于普遍个体化的特异条件"],
  verify="verified", frm="知识论 ch26 占位审计"),

 # ── 特征律线 ───────────────────────────────────────────
 dict(id="nbr-0121", ring="现象学",
  prop="视觉因其同时性、距离性与非介入性，成为西方哲学「理论」概念的模型，并因此塑造了整个真理观",
  alias=["视觉的高贵性", "The Nobility of Sight", "theoria 出自看", "距离化的感官塑造了真理观",
         "视觉优先于其他感官的哲学后果"],
  src=dict(author="Hans Jonas", title="The Nobility of Sight", year=1954),
  holds="任何「某一感官模态偏置塑造了一整套哲学」的判断",
  sep=["约纳斯已经把视觉—理论—真理观这条链条完整给出了；候选若只是重述这条链，即被 1:1 覆盖",
       "剩余只能来自：给出另一条模态（触觉/听觉）同等完整的对生链，或给出可裁决的跨文明对照"],
  verify="verified", frm="特征律线占位审计（这是特征律最贴的正主）"),

 dict(id="nbr-0122", ring="生态心理学",
  prop="知觉直接拾取环境光阵列中的不变量；无需内部表征的中介",
  alias=["不变量", "生态光学", "直接知觉", "可供性", "affordance", "知觉不需要推论"],
  src=dict(author="James J. Gibson", title="The Ecological Approach to Visual Perception", year=1979),
  holds="任何「知觉直接给出结构而非经由表征」的判断",
  sep=["吉布森的不变量在环境侧，主体只是拾取者；若候选要求主体侧有生成或认证动作，才有剩余"],
  verify="verified", frm="特征律线占位审计"),

 dict(id="nbr-0123", ring="哲学/方法论",
  prop="认识不是自我作用于对象（interaction），而是一个不可先行拆分的交易过程（transaction）",
  alias=["transaction", "交易", "知与所知", "主客不可先行拆分", "互动之外的第三种描述"],
  src=dict(author="John Dewey & Arthur F. Bentley", title="Knowing and the Known", year=1949),
  holds="任何「主客互动是本原、不可先行拆分」的判断",
  sep=["杜威—本特利已经把 self-action / interaction / transaction 三级区分给全了",
       "候选若主张主客互动为本原，须说明它与 transaction 的差别在哪一层（本体论层？发生学层？），否则被 1:1 覆盖"],
  verify="verified", frm="特征律线占位审计"),

 dict(id="nbr-0124", ring="认知科学",
  prop="人在整合视觉与触觉信息时，按各通道的可靠性做统计最优加权",
  alias=["最优多感官整合", "统计最优加权", "视触整合", "可靠性决定权重", "不是视觉总是压倒触觉"],
  src=dict(author="Marc O. Ernst & Martin S. Banks", title="Humans integrate visual and haptic information in a statistically optimal fashion", year=2002),
  holds="任何「视觉压倒触觉/某模态天然优先」的经验主张",
  sep=["这是对『视觉必然优先』的直接经验反例：权重随可靠性变化，视觉优先只是常见条件下的特例",
       "任何主张模态偏置的候选，必须先过这一条，否则经验层站不住"],
  verify="verified", frm="特征律线占位审计（这条是反例型占位者，用来卡经验主张）"),

 dict(id="nbr-0125", ring="实验心理学",
  prop="视觉与触觉冲突时，被试的判断被视觉俘获",
  alias=["视觉捕获", "visual capture", "视触冲突", "眼见为实的实验证据"],
  src=dict(author="Irvin Rock & Jack Victor", title="Vision and Touch: An Experimentally Created Conflict", year=1964),
  also=[dict(author="Francis B. Colavita", title="Human sensory dominance", year=1974)],
  holds="任何「视觉在冲突中胜出」的经验主张",
  sep=["经典结论已被 Ernst & Banks 2002 收窄为可靠性加权的特例；引用这一支时必须一并交代后续修正"],
  verify="verified", frm="特征律线占位审计"),

 dict(id="nbr-0126", ring="认知心理学",
  prop="人天然倾向于认为类别背后有一个不可见的本质，它决定了成员的表面特征",
  alias=["心理本质主义", "psychological essentialism", "本质的占位符", "类别背后有个看不见的东西",
         "essence placeholder"],
  src=dict(author="Douglas Medin & Andrew Ortony", title="Psychological Essentialism", year=1989),
  also=[dict(author="Susan A. Gelman", title="The Essential Child", year=2003)],
  holds="任何「人倾向于把关系性/过程性的东西读成实体」的判断",
  sep=["本质主义是认知默认倾向，是描述性的心理事实",
       "若候选主张某个特定制度或话语在制造这种读法（不是天然倾向而是被生产的），才有剩余"],
  verify="verified", frm="特征律线占位审计"),

 # ── 回写缺失线 ─────────────────────────────────────────
 dict(id="nbr-0141", ring="资源经济学",
  prop="把不可再生资源的租金全部再投资于可再生资本，才能维持代际间不下降的消费",
  alias=["哈特维克规则", "Hartwick rule", "资源租金再投资", "把地里挖出来的钱变成别的资本",
         "代际公平的储蓄条件"],
  src=dict(author="John M. Hartwick", title="Intergenerational Equity and the Investing of Rents from Exhaustible Resources", year=1977),
  holds="任何「取用之后必须回写、否则存量静默耗尽」的判断",
  sep=["哈特维克的对象是可计量的自然资本与实物投资，规则是规范性的会计条件",
       "若候选把回写推广到不可计量的基底（信任、判断力、发生条件），须给出该基底的可观测代理，否则只是类比"],
  verify="verified", frm="回写缺失线占位审计"),

 dict(id="nbr-0142", ring="发展经济学",
  prop="把自然资本折耗与人力资本投资计入储蓄，得到真实储蓄率；许多国家账面增长而真实储蓄为负",
  alias=["真实储蓄", "genuine saving", "adjusted net saving", "账面增长而实际在吃老本",
         "把折耗算进去之后是负的"],
  src=dict(author="Kirk Hamilton & Michael Clemens", title="Genuine Savings Rates in Developing Countries", year=1999),
  holds="任何「表面产出正常而底层存量在净流失」的判断",
  sep=["这一支给出了完整的核算框架与国别数据；候选若主张同构的『社会总回写率』，必须给出可核算的口径，否则被指为借词"],
  verify="verified", frm="回写缺失线占位审计"),

 dict(id="nbr-0143", ring="金融史",
  prop="信贷扩张的幅度是金融危机最稳健的预测变量；繁荣的规模预告了崩溃",
  alias=["信贷繁荣与崩溃", "Credit Booms Gone Bust", "杠杆积累预告危机", "繁荣期埋下的账"],
  src=dict(author="Moritz Schularick & Alan M. Taylor", title="Credit Booms Gone Bust", year=2012),
  holds="任何「繁荣期积累的未结算负债在后期集中兑现」的判断",
  sep=["这是有长时段面板数据的经验规律，变量明确可测",
       "候选若做跨域推广（把信贷换成别的存量），必须给出同等可测的自变量"],
  verify="verified", frm="回写缺失线占位审计"),

 dict(id="nbr-0144", ring="制度分析",
  prop="公共池塘资源可由使用者自组织的规则长期治理，既不必私有化也不必国家接管；八项设计原则",
  alias=["公共池塘资源", "自主治理", "八项设计原则", "既非市场也非国家", "使用者自己定规则"],
  src=dict(author="Elinor Ostrom", title="Governing the Commons", year=1990),
  holds="任何「自组织的本地规则维持公共存量」的判断",
  sep=["奥斯特罗姆的原则以规则的可监督、可分级惩罚、边界清晰为前提，本身是高度可读的制度设计",
       "若候选主张要保护的恰恰是不可被规则覆盖、不可言说的那部分，与她方向相反（见 nbr-0012 metis 一支）"],
  verify="verified", frm="回写缺失线占位审计"),

 dict(id="nbr-0145", ring="政治经济学",
  prop="地方官员在以经济增长为主要考核指标的晋升竞争中互相竞逐，激励结构决定了行为",
  alias=["晋升锦标赛", "官员激励", "以增长为考核的竞争", "可测指标决定地方行为"],
  src=dict(author="周黎安", title="中国地方官员的晋升锦标赛模式研究", year=2007),
  holds="任何「可测指标的激励挤出不可测事务」的中国语境判断",
  sep=["锦标赛模型的机制是相对绩效竞争；若候选主张的是被挤出的那一侧本身在改变什么算价值，才有剩余",
       "另见 nbr-0011（reactivity）与多任务委托代理一支"],
  verify="verified", frm="回写缺失线占位审计"),

 # ── 操作自盲线（补 nbr-0001 之外的） ──────────────────────
 dict(id="nbr-0161", ring="语言哲学",
  prop="眼睛不在视野之中；界限不能从界限之内被划出。规则不能规定自己的应用，遵守规则是一种实践",
  alias=["眼睛不在视野中", "5.633", "规则遵循悖论", "PI§201", "任何行动都可被解释为合乎规则",
         "解释不能终止解释"],
  src=dict(author="Ludwig Wittgenstein", title="Tractatus 5.633 / Philosophische Untersuchungen §201", year=1921),
  holds="任何「划界者无法在界内定位自己」「规则不能自证其用法」的判断",
  sep=["维特根斯坦的出路是实践与生活形式（不是更高一层的规则）",
       "若候选主张可以造一个装置把这个盲点部分对象化，须直面『那个装置自身的盲点又在哪』这一无穷后退"],
  verify="verified", frm="操作自盲线占位审计"),

 dict(id="nbr-0162", ring="社会学",
  prop="社会秩序由成员在每一刻的实践方法持续做出来；这些方法对成员自身是「看得见却注意不到」的",
  alias=["常人方法学", "ethnomethodology", "seen but unnoticed", "成员方法", "秩序是被做出来的",
       "破坏实验"],
  src=dict(author="Harold Garfinkel", title="Studies in Ethnomethodology", year=1967),
  holds="任何「维持秩序的操作对操作者自己不可见」的判断",
  sep=["加芬克尔的不可见是注意力层的（可被破坏实验逼出来），不是构成性的不可能",
       "若候选主张的是构成性的不可对象化（无论怎么做都逼不出来），与他方向不同"],
  verify="verified", frm="操作自盲线占位审计"),

 dict(id="nbr-0163", ring="科学知识社会学",
  prop="反身性一旦被当作方法要求，就会陷入无穷后退；反身性研究本身同样需要被反身地研究",
  alias=["反身性论题", "The Reflexive Thesis", "反对反身性", "自我指涉的无穷后退",
         "研究者的位置无法被自己的方法安置"],
  src=dict(author="Malcolm Ashmore", title="The Reflexive Thesis", year=1989),
  also=[dict(author="Michael Lynch", title="Against Reflexivity as an Academic Virtue", year=2000)],
  holds="任何「自我审查的装置同样需要被审查」的判断",
  sep=["这一支的结论多是消解性的：反身性作为德性被质疑，出路是回到实践",
       "若候选主张某种一次性的、可操作的自我解除装置（而非无穷后退），须说明它凭什么在某一层停下来"],
  verify="verified", frm="操作自盲线占位审计"),

 dict(id="nbr-0164", ring="心灵哲学",
  prop="任何客观化都从某个视角出发；把一切都对象化的「来自无处的观点」无法容纳观察者自身",
  alias=["来自无处的观点", "The View from Nowhere", "客观化的限度", "主观视角无法被完全对象化"],
  src=dict(author="Thomas Nagel", title="The View from Nowhere", year=1986),
  holds="任何「彻底客观化会遗漏观察者本身」的判断",
  sep=["内格尔的对象是主观经验的不可还原（现象意识）",
       "若候选的对象是操作/裁决动作的不可对象化（不涉及现象意识），须把这条线划清"],
  verify="verified", frm="操作自盲线占位审计"),

 # ── 后果回路线 ─────────────────────────────────────────
 dict(id="nbr-0181", ring="心理学",
  prop="反复经历自己的行动与结果无关之后，个体停止尝试，即使后来情境已经可控",
  alias=["习得性无助", "learned helplessness", "行动与结果脱钩", "不可控经验的后效",
         "后来能控了也不试了"],
  src=dict(author="Martin E. P. Seligman & Steven F. Maier", title="Failure to Escape Traumatic Shock", year=1967),
  holds="任何「行动与后果脱钩导致能力停转」的判断",
  sep=["习得性无助的机制在动机与预期（个体学到了不可控），撤除不可控后可被再学习逆转",
       "若候选主张的是能力赖以生成的条件本身被取消（不是学到了不可控，而是从未被要求执行过那个操作），才有剩余"],
  verify="verified", frm="后果回路线占位审计"),

 dict(id="nbr-0182", ring="组织行为学",
  prop="技能多样性、任务完整性、任务重要性、自主性与反馈五项核心特征决定工作的内在动机",
  alias=["工作特征模型", "job characteristics model", "任务完整性", "反馈与自主性",
         "看得到自己那份活的整体"],
  src=dict(author="J. Richard Hackman & Greg R. Oldham", title="Motivation through the Design of Work", year=1976),
  holds="任何「看不到自己行动的后果导致动机与能力衰减」的判断",
  sep=["哈克曼—奥尔德姆是可操作的工作设计变量，补救方向是重新设计岗位",
       "若候选主张的损失不能由这五项的任一项恢复，须指出它落在五项之外的哪一处"],
  verify="verified", frm="后果回路线占位审计"),

 dict(id="nbr-0183", ring="公共行政",
  prop="公民参与有阶梯：从操纵、安抚到伙伴关系与公民控制；下层几级是有参与之名而无权力之实",
  alias=["公民参与阶梯", "ladder of citizen participation", "假参与", "安抚",
         "有参与之名无决定之实"],
  src=dict(author="Sherry R. Arnstein", title="A Ladder of Citizen Participation", year=1969),
  holds="任何「参与形式存在而决定权未转移」的判断",
  sep=["阿恩斯坦的刻度是权力的实际转移程度，是规范性的评价尺",
       "若候选主张的是即使权力真的转移、某种发生仍不出现，才有剩余"],
  verify="verified", frm="后果回路线占位审计"),

 dict(id="nbr-0184", ring="动机心理学",
  prop="自主、胜任与关联三项基本需要的满足决定内在动机；外部控制会挤出内在动机",
  alias=["自我决定论", "SDT", "内在动机被外部奖励挤出", "过度理由效应", "自主胜任关联"],
  src=dict(author="Edward L. Deci & Richard M. Ryan", title="Intrinsic Motivation and Self-Determination in Human Behavior", year=1985),
  holds="任何「外部控制/奖励侵蚀内在驱动」的判断",
  sep=["SDT 的损失可逆：撤除控制后内在动机可恢复",
       "若候选主张不可逆（撤除后恢复幅度与暴露时长负相关），方向可裁决"],
  verify="verified", frm="后果回路线占位审计"),

 dict(id="nbr-0185", ring="社会哲学",
  prop="人的自我关系依赖于被他人承认；承认的三种形式（爱、法权、团结）各对应一种自我关系",
  alias=["承认理论", "Anerkennung", "为承认而斗争", "自我关系依赖他人承认", "蔑视与受损的自我关系"],
  src=dict(author="Axel Honneth", title="Kampf um Anerkennung", year=1992, zh="为承认而斗争"),
  holds="任何「不被承认导致自我关系受损」的判断",
  sep=["霍耐特的承认是规范性的社会关系范畴，补救方向是承认秩序的改造",
       "若候选主张的是生理层或发生层的结算（不是自我关系受损而是某个过程无法完成），才有剩余"],
  verify="verified", frm="后果回路线占位审计"),

 dict(id="nbr-0186", ring="人格心理学",
  prop="人对强化来源的归因存在内外控倾向的稳定个体差异",
  alias=["控制点", "locus of control", "内控外控", "把结果归因于自己还是环境"],
  src=dict(author="Julian B. Rotter", title="Generalized Expectancies for Internal versus External Control of Reinforcement", year=1966),
  holds="任何「个体是否把后果归到自己头上」的判断",
  sep=["罗特的控制点是稳定的个体差异变量（特质）",
       "若候选主张的是被制度性地取消了归因通道（不是个体差异而是结构条件），才有剩余"],
  verify="verified", frm="后果回路线占位审计"),

 # ── 引擎室十四位（补 0028/0033 之外的） ─────────────────────
 dict(id="nbr-0201", ring="社会学",
  prop="惯习是被结构塑造又生产实践的身体化性情系统；它使人自发地做出符合其位置的行动",
  alias=["惯习", "habitus", "身体化的性情系统", "结构被内化为身体", "自发地做出符合位置的事"],
  src=dict(author="Pierre Bourdieu", title="Le Sens pratique", year=1980, zh="实践感"),
  holds="任何「结构在人身上预装、行动者自发再生产它」的判断",
  sep=["惯习是历史沉积的、跨情境的性情，重心在再生产",
       "若候选主张的是某一次具体的、可定位的预装动作（不是长期沉积而是事前安置在工具里），才有剩余",
       "⚠ 这是『收编/预装』类候选最常被 1:1 覆盖的一家，50 字压缩后必查"],
  verify="verified", frm="引擎室十四位"),

 dict(id="nbr-0202", ring="性别理论",
  prop="身份不是先在的实体，而是通过反复的操演被生产出来的效果；颠覆只能在重复中发生",
  alias=["操演性", "performativity", "性别麻烦", "身份是重复的效果", "颠覆只能在重复内部"],
  src=dict(author="Judith Butler", title="Gender Trouble", year=1990, zh="性别麻烦"),
  holds="任何「反抗的工具本身已被它所反抗之物构成」的判断",
  sep=["巴特勒的颠覆在重复的内部，承认无外部立足点",
       "若候选主张的是事前预装（收编先于反抗在场）而非重复中的构成，须给出可裁决的时序判据"],
  verify="verified", frm="引擎室十四位"),

 dict(id="nbr-0203", ring="政治哲学",
  prop="规训社会正在被控制社会取代：封闭空间让位于连续调制，个体变成可分割的数据流",
  alias=["控制社会", "sociétés de contrôle", "连续调制", "可分体", "dividual", "无墙的控制"],
  src=dict(author="Gilles Deleuze", title="Post-scriptum sur les sociétés de contrôle", year=1990),
  holds="任何「控制不再靠围墙而靠连续的调制」的判断",
  sep=["德勒兹是时代诊断，粒度粗、无经验判据",
       "候选若只是把它换词重述即被覆盖；剩余必须来自可观测的机制与可裁决的预测"],
  verify="verified", frm="引擎室十四位"),

 dict(id="nbr-0204", ring="政治经济学",
  prop="面对组织衰退，成员有退出与呼吁两条路；忠诚影响两者的相对使用",
  alias=["退出与呼吁", "Exit, Voice, and Loyalty", "用脚投票还是开口", "退出的便利抑制了呼吁"],
  src=dict(author="Albert O. Hirschman", title="Exit, Voice, and Loyalty", year=1970),
  holds="任何「退出通道的存在改变了发声与坚持」的判断",
  sep=["赫希曼的两条路都以成员对衰退有察觉为前提",
       "若候选主张的是察觉本身被取消（连可以呼吁的那个位置都不再产生），才有剩余"],
  verify="verified", frm="引擎室十四位"),

 dict(id="nbr-0205", ring="批判理论",
  prop="主人的工具拆不了主人的房子",
  alias=["主人的工具", "The Master's Tools Will Never Dismantle the Master's House",
         "用体制的工具反体制注定失败", "工具本身带着它所服务的秩序"],
  src=dict(author="Audre Lorde", title="The Master's Tools Will Never Dismantle the Master's House", year=1979),
  holds="任何「反抗因借用了对方的工具而注定被收编」的判断",
  sep=["洛德是与该判断同向的占位者，不是可被推开的对手——引用时必须承认同向并说明本文多出什么",
       "⚠ 引擎室那次的近邻表点了六位『事后收编』派（都能被推开），唯独漏掉这一位与马尔库塞——检索口径缺『先找同向占位者』"],
  verify="verified", frm="引擎室十四位（漏掉的那两位之一）"),

 dict(id="nbr-0206", ring="批判理论",
  prop="在既有权力格局下，普遍的宽容实际服务于压迫；纯粹的宽容是压抑性的",
  alias=["压抑性宽容", "repressive tolerance", "宽容本身在维持压迫", "允许一切异议等于消解异议"],
  src=dict(author="Herbert Marcuse", title="Repressive Tolerance", year=1965),
  holds="任何「开放/包容的形式本身在执行封闭」的判断",
  sep=["马尔库塞同样是同向占位者；候选须说明本文多出的机制（例如事前预装 vs 事后吸纳）"],
  verify="verified", frm="引擎室十四位（漏掉的那两位之二）"),

 dict(id="nbr-0207", ring="经济学",
  prop="当任务的某些维度可测而另一些不可测，对可测维度的高强度激励会挤出不可测维度的努力",
  alias=["多任务委托代理", "multitask principal-agent", "可测的挤出不可测的",
         "为什么不能只按可考核的部分给激励", "激励强度与可测性的匹配"],
  src=dict(author="Bengt Holmström & Paul Milgrom", title="Multitask Principal-Agent Analyses", year=1991),
  holds="任何「可计量的部分挤掉不可计量的部分」的判断",
  sep=["其处方是降低可测维度的激励强度（弱激励），是一个内生的最优合约问题",
       "若候选的处方是另开一条以可审视性为对象的端口（保持合规轨、增设活性轨），方向不同、可用三臂试验裁决"],
  verify="verified", frm="B4 制度性可见度补切时点名，尚未入库"),
]
