# -*- coding: utf-8 -*-
"""近邻库种子·A 批：2026-07-31 产线实战中真实咬到的占位者。

每张卡以「命题空间」为主键，不以学科或人名为主键——候选是以命题的形态到达的。
alias 是成败关键：50 字压缩后的候选要能凭表述变体检出这张卡。
"""

CARDS_A = [
 dict(id="nbr-0001", ring="社会系统论",
  prop="划界者不能在自己所划的界内安置自己；系统的操作对自身的盲点是构成性的，不是待修的缺陷",
  alias=["观察者盲点", "规则不能规定自身的应用", "元操作未被对象化", "反身性的无穷后退",
         "系统看不见自己看不见的东西", "二阶观察才看得见一阶的盲区"],
  src=dict(author="Niklas Luhmann", title="Die Wissenschaft der Gesellschaft", year=1990, zh="社会的科学"),
  also=[dict(author="Heinz von Foerster", title="Observing Systems", year=1981),
        dict(author="George Spencer-Brown", title="Laws of Form", year=1969)],
  holds="任何「制定规则者无法把自己纳入规则」类型的判断",
  sep=["卢曼的盲点是操作的构成条件、无法通过任何努力消除；若候选主张盲点可经由某种制度设计被消除或转移，才有剩余",
       "卢曼是系统层的、无主体；若候选的承重点在个体的自欺或动机，须说明为何不能被系统层吸收"],
  verify="verified", frm="操作自盲审计（真跑 I=115 的直接病因，全篇未出现）"),

 dict(id="nbr-0002", ring="组织理论",
  prop="组织不面对现成的环境；它通过行动把环境做出来，再对自己做出来的那个东西作出反应",
  alias=["enactment", "生成性环境", "行动创造环境再回应它", "组织自己搅动出可解读的材料",
         "先做后懂", "回溯地读出秩序"],
  src=dict(author="Karl E. Weick", title="Sensemaking in Organizations", year=1995, zh="组织中的意义建构"),
  holds="任何「以行动换取可解读材料、再据以决定下一步」的判断",
  sep=["enactment 是单边的：秩序由行动者回溯建构，环境不提供答案；若候选要求对面站着一个被迫作答的主体（有自己意图的对手），才有剩余",
       "判据：把对手换成不作答的环境（地形、气象、无对抗的市场空白），enactment 照样成立"],
  verify="verified", frm="高鹏《发问式决策》补切（原稿文献表有 Weick 1995，正文从未把它当对手）"),

 dict(id="nbr-0003", ring="军事学",
  prop="以一次真实的攻击去逼迫对方暴露兵力、部署与意图",
  alias=["火力侦察", "reconnaissance in force", "以战代侦", "用行动换情报", "试探性进攻"],
  src=dict(author="—", title="reconnaissance in force（军事学通用术语）", year=None),
  holds="任何「用行动逼对方暴露」的判断",
  sep=["火力侦察是手段层：目标不变，侦察只填计划所需的空白参数",
       "判据：行动之后被修改的若只是路径与参数而目标存续，即是火力侦察；被注销的是目标本身且注销是自动的，才是别的东西"],
  verify="verified", frm="高鹏《发问式决策》补切"),

 dict(id="nbr-0004", ring="政治法学",
  prop="常规规范无法涵摄的情形上作出决断的权力，先于并奠基于规范，而非由规范授予",
  alias=["例外状态", "主权者就是对例外状态作出决断的人", "法秩序无法自我穷尽",
         "断口上的决断", "常规程序失效时谁来决断"],
  src=dict(author="Carl Schmitt", title="Politische Theologie", year=1922, zh="政治神学"),
  holds="任何「常规通道失效后靠非常规决断脱困」的判断",
  sep=["施密特的决断者站在规范之外，正当性不来自任何条文；若候选严格要求被走的那条路仍在制度之内、合法、可被公开指认，才有剩余",
       "判据：逆转之后能否被纳入制度记忆（合法接口）还是只沉淀为个人权威（例外决断）"],
  verify="verified", frm="高鹏《回路重启》补切"),

 dict(id="nbr-0005", ring="控制论",
  prop="控制者的状态多样性必须不低于被控系统的扰动多样性",
  alias=["必要多样性定律", "requisite variety", "只有多样性才能吸收多样性", "冗余通道", "break-glass 应急权限"],
  src=dict(author="W. Ross Ashby", title="An Introduction to Cybernetics", year=1956),
  holds="任何「预留通道以应对超出常规的扰动」的判断",
  sep=["break-glass 是被设计并持续维护的：有演练、有审计、启用者不承担正当性风险",
       "判据：启用者是否必须独自承担『破坏集体程序』的嫌疑——承担者说明那条通道是被遗忘的历史残留，不是设计的冗余"],
  verify="verified", frm="高鹏《回路重启》补切"),

 dict(id="nbr-0006", ring="组织理论",
  prop="当「我们是谁、在干什么」这套框架突然失效，组织连同其成员的行动能力一起解体",
  alias=["意义建构的崩溃", "collapse of sensemaking", "曼恩峡谷", "角色系统解体",
         "命令下达了却没人执行", "框架失效导致协同瓦解"],
  src=dict(author="Karl E. Weick", title="The Collapse of Sensemaking in Organizations: The Mann Gulch Disaster", year=1993),
  holds="任何「旧框架被当众判死之后组织发生什么」的判断",
  sep=["韦克要解释的是崩溃之后的解体，补救方向是让崩溃不要发生（更有韧性的意义建构）",
       "若候选要解释的是崩溃发生之后没有解体的那一类，并预测崩溃深度与解体概率非单调，才有剩余"],
  verify="verified", frm="高鹏《基底重启》补切"),

 dict(id="nbr-0007", ring="认识论/人类学",
  prop="改变「如何学习」的那套前提本身；极为罕见，常伴人格解体，多发生在生存危机中",
  alias=["Learning III", "学习层级", "改变学习的前提", "元前提的更换", "第三层学习"],
  src=dict(author="Gregory Bateson", title="Steps to an Ecology of Mind", year=1972, zh="心灵生态学步骤"),
  holds="任何「元前提被整个更换」的判断",
  sep=["贝特森给的是认识论刻度（变化发生在第几层），不给发生条件、不给组织条件；他的例证是个体皈依与治疗性突破",
       "若候选提供的是组织层的发生条件（须公开证伪、须无外援、须从最低生存目标逐句拼出），才有剩余"],
  verify="verified", frm="高鹏《基底重启》补切"),

 dict(id="nbr-0008", ring="心理学",
  prop="自我控制像一块肌肉，用过之后会疲劳，随后的自控任务表现随之下降",
  alias=["自我损耗", "ego depletion", "意志力有限资源", "自控疲劳", "付出努力后表现下降"],
  src=dict(author="Roy F. Baumeister et al.", title="Ego Depletion: Is the Active Self a Limited Resource?", year=1998),
  holds="任何「某种心理资源被支出后短期无法补足」的判断",
  sep=["自我损耗由付出努力触发——任务越费劲损耗越深，与成败无关",
       "判据：努力量×成败 2×2 正交设计。损耗沿努力维度分布；若候选预测沿成败维度分布（省力的胜利同样抽空），才有剩余",
       "⚠ 该效应近年有重复危机，援引时须一并交代，不可当作稳固地基"],
  verify="verified", frm="高鹏《成功之死·活性假象》补切"),

 dict(id="nbr-0009", ring="人机系统",
  prop="自动化接管之后，操作者恰恰在最需要他的时刻已经失去那个能力，而该能力只能靠亲手做常规工作练出来",
  alias=["自动化的讽刺", "Ironies of Automation", "去技能化", "接管导致的能力萎缩",
         "越自动化越依赖人的应急能力却越练不出", "代偿掉的是锻造判断力的那段"],
  src=dict(author="Lisanne Bainbridge", title="Ironies of Automation", year=1983),
  holds="任何「外部系统接管之后内在能力不可逆消解」的判断",
  sep=["Bainbridge 的对象是操作技能与情境意识，机制是练习机会的丧失",
       "若候选主张被代偿的不是操作技能而是别的东西（判断力的锻造环节、时序完整性、承担的默会结构），须说明它为何不能被『练习机会丧失』吸收"],
  verify="verified", frm="⚠ 同一家在同一日被两条线各漏一次：高鹏《法外之骨》与胡敏 12 篇代理组"),

 dict(id="nbr-0010", ring="知识社会学",
  prop="社会实在从人的活动中被造出来，随后作为坚硬的、外在于人的东西反过来面对他",
  alias=["客观化", "物化", "reification", "人造之物显得像自然事实", "外化—客观化—内化",
         "被造出来的东西显得不可更改"],
  src=dict(author="Peter L. Berger & Thomas Luckmann", title="The Social Construction of Reality", year=1966, zh="现实的社会建构"),
  holds="任何「硬是被造出来的、而非本来就硬」的判断",
  sep=["物化的机制是遗忘作者身份（人忘了这是自己造的）",
       "若候选主张硬来自持续进行中的、不可逆的自我切割动作（而非遗忘），才有剩余"],
  verify="verified", frm="张琼《互裁》未切（该篇已由并发线发布，补切待办）"),

 dict(id="nbr-0011", ring="组织社会学",
  prop="把不可通约的东西转换成可通约的度量；被度量者随即改变自己以迎合度量，度量因而改造了它所测的世界",
  alias=["commensuration", "reactivity", "排名的反应性", "指标反过来塑造被测者",
         "度量创造了它声称只在描述的现实", "可比性是被制造出来的"],
  src=dict(author="Wendy N. Espeland & Michael Sauder", title="Rankings and Reactivity: How Public Measures Recreate Social Worlds", year=2007),
  also=[dict(author="Espeland & Stevens", title="Commensuration as a Social Process", year=1998)],
  holds="任何「指标不只是测量、还在定义什么算价值」的判断",
  sep=["反应性的机制是被测者的策略性适应，价值本身仍被预设为先在",
       "若候选主张被指标伤害的那个价值并非先在、而是在争夺中才成形，才有剩余"],
  verify="verified", frm="张琼《裁决竞逐》未切（该篇已由并发线发布，补切待办）"),

 dict(id="nbr-0012", ring="政治人类学",
  prop="国家为治理必须把复杂、地方性、难以编码的现实简化为标准化可清点的格式；不进入格式的东西在国家眼里等于不存在",
  alias=["可读性", "legibility", "国家的视角", "只看得见可被度量之物", "简化图式反过来改造现实",
         "metis", "地方性实践智慧无法被编码"],
  src=dict(author="James C. Scott", title="Seeing Like a State", year=1998, zh="国家的视角"),
  holds="任何「制度只能识别可计数之物、看不见其余」的判断",
  sep=["斯科特的破坏力来自主动简化与改造——国家动手把现实重塑得可读",
       "若候选的破坏力只来自持续的不收录（被蒸发的东西没有被替换、只是没被记进账），才有剩余",
       "metis 一支的补救方向是让不可读之物被承认；若候选要求的是在明知看不见的前提下为它留出不被覆盖的位置（容纳而非承认），才有剩余"],
  verify="verified", frm="高鹏《庄严的错位》与张琼《混沌喂养》两处各漏一次"),

 dict(id="nbr-0013", ring="伦理学/现象学",
  prop="他者面容的显现向我提出一个我无法推卸、也无人能代我承担的伦理要求；责任先于我的任何选择",
  alias=["面容", "le visage", "不可推卸的责任", "不对称的伦理要求", "他者先于自我",
         "无人能代我回答"],
  src=dict(author="Emmanuel Levinas", title="Totalité et Infini", year=1961, zh="总体与无限"),
  holds="任何「不可代理的责任由他者在场逼出」的判断",
  sep=["列维纳斯的不可代理先于情境，无条件，制度至多遮蔽不能消灭",
       "若候选严格依赖若干情境条件的叠合（抽掉任一条裁决即不发生），才有剩余",
       "判据：代理机制撤出后，自发承担是否可恢复——不可恢复的那部分是列维纳斯覆盖不到的"],
  verify="verified", frm="张琼《被裁决》补切"),

 dict(id="nbr-0014", ring="科学哲学/社会本体论",
  prop="人的分类不像自然种类那样被动等着被发现；被分类的人知道自己被如何分类并据此改变自己，改变后又迫使分类被修订",
  alias=["回路效应", "looping effects", "making up people", "造人", "分类造出被分类的人",
         "互动种类", "人反过来改变了关于他的分类"],
  src=dict(author="Ian Hacking", title="Making Up People", year=1986),
  holds="任何「自我在与外部反馈的互动中被生成」的判断",
  sep=["哈金的回路两端是人与一套公共分类：分类可命名、可查、可被反抗或认领，主体的能动性环节是核心",
       "若候选的回路另一端是只对一个人成立、不公开、无名的即时反馈（当事人无从知道自己被如何分类，因而无法协商），能动性环节被结构性取消，才有剩余"],
  verify="verified", frm="张琼《接生》补切"),

 dict(id="nbr-0015", ring="社会心理学",
  prop="我关于我自己的观念，来自我想象中他人对我的看法",
  alias=["镜中我", "looking-glass self", "泛化的他人", "从他人的眼睛里看自己", "他人的评价内化为自我"],
  src=dict(author="Charles Horton Cooley", title="Human Nature and the Social Order", year=1902),
  also=[dict(author="George Herbert Mead", title="Mind, Self and Society", year=1934)],
  holds="任何「自我形象由外部反馈塑成」的判断",
  sep=["库利的镜子是被想象出来的——想象由我完成，因而保留了我的诠释、误读与自我辩护空间",
       "若候选的反射是已经量化并送达的实际结果（无需想象、无从误读），诠释空间的消失才是剩余"],
  verify="verified", frm="张琼《接生》补切"),

 dict(id="nbr-0016", ring="精神分析",
  prop="承受者接住尚未成形、无法被思考的原始经验，在自己内部代谢它们，使之成为可被思考的东西再返还",
  alias=["涵容", "containment", "container/contained", "alpha 功能", "替对方消化他还想不了的东西"],
  src=dict(author="Wilfred R. Bion", title="Learning from Experience", year=1962),
  holds="任何「陪伴者承受对方无法承受之物」的判断",
  sep=["比昂的涵容者是加工者：他具备被涵容者尚不具备的加工能力，成果由他返还",
       "若候选的承受者不加工、也不具备对方所缺的能力（他同样不知道这团东西会变成什么），提供的是『在无人能代谢时不退场』，才有剩余",
       "判据：无模板情境中，陪伴者的命名频次与被陪者自主探索量的相关方向——比昂预测正相关"],
  verify="verified", frm="张琼《长陪》补切"),

 dict(id="nbr-0017", ring="社会学/手艺研究",
  prop="能力来自与材料阻力的长期协商；材料的不服从是技艺得以生长的条件",
  alias=["材料的阻力", "material resistance", "匠人", "为做好而做好", "与不服从的材料搏斗"],
  src=dict(author="Richard Sennett", title="The Craftsman", year=2008, zh="匠人"),
  holds="任何「能力在与具体材料的长期对抗中沉积」的判断",
  sep=["桑内特的匠人朝着做好一件东西去搏斗，阻力的教育意义来自它挡在明确的成品目标前",
       "若候选要求非工具性沉浸（没有『做好』的尺度在前面等），才有剩余"],
  verify="verified", frm="张琼《底劲》补切"),

 dict(id="nbr-0018", ring="心灵哲学",
  prop="认知过程可以合法地延展到颅外的工具与环境；不存在必须被守在皮肤之内的「真正的」认知",
  alias=["延展心智", "extended mind", "外部载体就是记忆本身", "认知的边界外移",
         "工具是心智的一部分", "耦合系统论证"],
  src=dict(author="Andy Clark & David Chalmers", title="The Extended Mind", year=1998),
  holds="任何「外部装置接手内在功能之后是否算损伤」的判断",
  sep=["延展心智处理的是功能的实现位置：只要耦合稳定、可及、可信，在脑内还是脑外无关紧要",
       "若候选关心的不是功能实现在哪里，而是产生新功能的那个转化力本身是否停转，才有剩余",
       "判据：给一个外部载体无法覆盖的新问题（无先例、无模板），延展心智预测长期使用者不劣于对照"],
  verify="verified", frm="张琼《活壳》补切"),

 dict(id="nbr-0019", ring="存在论",
  prop="唯有先行到死亡这一最本己的、不可逾越的可能性之中，此在才从沉沦于常人的状态被唤回",
  alias=["向死而在", "Sein zum Tode", "先行到死", "终结的确定性使存在获得整体性",
         "非本真地把死亡当作总有一天的事件"],
  src=dict(author="Martin Heidegger", title="Sein und Zeit", year=1927, zh="存在与时间"),
  holds="任何「可能终结的意识是意义得以持续的前提」的判断",
  sep=["海德格尔靠死亡的必然性发力：死是必然的，不确定的只是何时",
       "若候选靠偶然性发力（可能死也可能不死、存续不被担保，一旦获得『反正死不了』的确信机制即失效），把它改成必然的会使机制失效而非增强，才有剩余",
       "判据：『已知终局』的情境（绝症、有明确期限的分离）意义强度是升还是降——两者预测相反"],
  verify="verified", frm="张琼《关系的重力/死亡感》补切"),

 dict(id="nbr-0020", ring="存在论",
  prop="此在是人的存在方式的整体命名；它没有程度、不会时有时无，本真与非本真是它的两种样式而非它的有无",
  alias=["此在", "Dasein", "亲在（旧译）", "在世存在", "存在方式而非属性"],
  src=dict(author="Martin Heidegger", title="Sein und Zeit", year=1927, zh="存在与时间"),
  holds="任何用「亲在／此在／在场」命名一种存在论能力的判断",
  sep=["此在无程度、不可被外部条件直接开关；本真性无法被条件调节",
       "若候选主张的是一项可被条件维持、可以停转、可以重启的运作（有可测阈值），才有剩余；且必须先澄清命名与 Dasein 的译名关系"],
  verify="verified", frm="张琼《亲在》补切（该命名在汉语语境会直接向 Dasein 招手）"),

 dict(id="nbr-0021", ring="科学技术论",
  prop="人把任务委托给非人行动者；任务被完成了，但完成的方式以及它对人的要求都被改写",
  alias=["委托", "delegation", "减速带替代交警", "门弹簧替代守门人", "行动是人与非人组成的链条的属性"],
  src=dict(author="Bruno Latour", title="Where Are the Missing Masses?", year=1992),
  holds="任何「动作被外部装置接手后性质随之改变」的判断",
  sep=["委托预设一件已经被规定好的任务：关门这件事在门弹簧之前就存在，委托改变执行者不改变『要做什么』",
       "若候选所跳过的是『要做什么』尚未成形的那个阶段（轮廓要在浸泡于不确定中才获得），才有剩余",
       "判据：撤除装置后，委托预测任务回到人身上被重新执行；若候选预测连那团需要被处理的东西都不再生成，方向相反"],
  verify="verified", frm="张琼《算法替代》补切"),

 dict(id="nbr-0022", ring="医学社会学",
  prop="医学的目光从病床上的病人移向整个人群，健康与疾病之间的界线被风险因素溶解，人人被纳入持续监测",
  alias=["监视医学", "surveillance medicine", "健康与疾病成为连续统", "正常本身需要不断被查验",
         "风险因素取代症状"],
  src=dict(author="David Armstrong", title="The Rise of Surveillance Medicine", year=1995),
  holds="任何「医学在没有病的地方开始工作」的判断",
  sep=["阿姆斯特朗的判断是界线被溶解成一条连续谱线，人人都在某个位置",
       "若候选主张界线不但没消失、反而多了一条（被制度操作沉淀出第三个身份），才有剩余",
       "判据：指南切点两侧客观风险几乎相同的两组人，其自我描述与随访行为是平滑过渡还是非线性断裂"],
  verify="verified", frm="胡敏《临界间》补切"),

 dict(id="nbr-0023", ring="医学社会学",
  prop="处于风险之中本身已成为一种被亲身经历的状态，风险与疾病的经验界限正在模糊",
  alias=["作为经验的风险", "risk as experience", "高危者的焦虑与预防性干预", "风险体验向疾病体验靠拢"],
  src=dict(author="Robert A. Aronowitz", title="Risky Medicine", year=2015),
  holds="任何「被标记为高风险之后过的是什么日子」的判断",
  sep=["阿罗诺维茨的路径是经验现象学的：解释力来自个体侧的心理与文化过程",
       "若候选的路径是制度本体论的（一个人即使毫不在意，电子病历里的那条警报不因心态而消失），才有剩余",
       "判据：心理干预有效降低焦虑之后，检查频次/用药起始率/保费是否同步回归"],
  verify="verified", frm="胡敏《临界间》补切"),

 dict(id="nbr-0024", ring="生命政治",
  prop="分子生物学与遗传风险技术造就了一类新的人：他没有病，但被自己的生物学标记为易感，并被要求据此管理现在与未来",
  alias=["易感主体", "susceptible self", "生命本身的政治", "遗传风险身份", "被赋予自我管理任务的健康人"],
  src=dict(author="Nikolas Rose", title="The Politics of Life Itself", year=2007, zh="生命本身的政治"),
  holds="任何「风险标记如何改变一个没有病的人」的判断",
  sep=["罗斯的易感主体是被赋予任务的：处境是责任的增加，重心在自主性、选择与生命最优化",
       "若候选是一次纯粹的减法（不给任何任务，取消的是一种此前一直在运转却从未被察觉的状态），才有剩余",
       "判据：在明确拒绝一切随访与用药、自评『完全不当回事』的那一组里，伤害是否照常成立"],
  verify="verified", frm="胡敏《豁免权的注销》补切"),

 dict(id="nbr-0025", ring="哀伤研究",
  prop="某些丧失因不被社会承认为「有资格的丧失」，其哀伤无法进入任何公开的承认通道，因而无法完成，转为慢性身心症状",
  alias=["被剥夺的哀伤", "disenfranchised grief", "不被承认的丧失", "没有出口的哀伤",
         "照料者对尚未死去之人的丧失"],
  src=dict(author="Kenneth J. Doka", title="Disenfranchised Grief: Recognizing Hidden Sorrow", year=1989),
  holds="任何「未被结算的情感投入转为躯体症状」的判断",
  sep=["多卡的机制发生在丧失之后：丧失已成立，问题在于善后找不到社会承认的出口；补救方向是提供承认通道",
       "若候选发生在过程之中（还没有任何丧失，对方就在眼前活着），被卡住的是应答而非哀伤的表达，才有剩余",
       "判据：社会承认充分而对方状态持续无改善的一组，症状是否照常"],
  verify="verified", frm="胡敏《祈应核》《结算饥饿》补切"),

 dict(id="nbr-0026", ring="组织心理学",
  prop="人力求获取、保有并保护资源；资源净损失是应激的根本来源，损失比获得更具冲击力，并自我加速形成损失螺旋",
  alias=["资源保存理论", "COR", "conservation of resources", "损失螺旋", "投入未被补充即损失",
         "资源净流出导致耗竭"],
  src=dict(author="Stevan E. Hobfoll", title="Conservation of Resources: A New Attempt at Conceptualizing Stress", year=1989),
  holds="任何「持续投入而不被补充导致耗竭」的判断",
  sep=["COR 的核算单位是资源存量：只要投入未被等量补充，损失即成立，与投入是否『抵达』无关",
       "若候选的核算单位是某种结清/冲销（同等资源补充下，对方有无可感知的应答决定结果），才有剩余",
       "判据：同等资源补充干预下，改善组与无改善组的耗竭改善幅度是否相近"],
  verify="verified", frm="胡敏《生理托管》《结算饥饿》《应答–功能解耦》补切"),

 dict(id="nbr-0027", ring="认识论/女性主义",
  prop="当社会的集体诠释资源存在结构性空缺，某些群体的经验无法被自己或他人理解与表达",
  alias=["诠释学不正义", "hermeneutical injustice", "集体诠释资源的空缺",
         "在这个词被造出来之前说不清自己遭遇了什么", "作为知者的资格被削弱"],
  src=dict(author="Miranda Fricker", title="Epistemic Injustice: Power and the Ethics of Knowing", year=2007),
  holds="任何「命名之前的经验说不出来」的判断",
  sep=["弗里克定位为认识论上的不正义：损害在于承受者作为知者的资格被削弱，补救是补足集体诠释资源",
       "若候选定位为发生学事件（损害不在于已有经验说不出，而在于能承载它的主体尚未被生成），才有剩余",
       "判据：诠释资源齐备的社会里，弗里克预测不正义缓解；若候选预测资源越丰盈原创命名率反而越低（新体验被就近归入现成格子），方向相反"],
  verify="verified", frm="高鹏《自生式命名》补切"),

 dict(id="nbr-0028", ring="社会学",
  prop="支配最有效的形态不是外部强制，而是被支配者把支配结构的分类图式内化为自己的感知图式，从而自愿把自己排除在某些场域之外",
  alias=["象征暴力", "symbolic violence", "位置感", "sens de sa place", "那不是给我这种人的",
         "自我排除", "误识"],
  src=dict(author="Pierre Bourdieu", title="La Distinction / Le Sens pratique", year=1979, zh="区分／实践感"),
  holds="任何「我不配」类型的自我审查判断",
  sep=["象征暴力内化的是关于人的等级图式，资格与出身、教育、资本绑定，因而分布沿阶层分层",
       "若候选内化的是关于对象的完整定义（不区分说话者是谁，只审查这一句够不够格），排异跨阶层同质，才有剩余",
       "判据：控制社会位置后，自我审查主要由发言者的场域资本解释还是由内容成熟度自评解释"],
  verify="verified", frm="高鹏《茧室》补切"),

 dict(id="nbr-0029", ring="文学理论",
  prop="作品的意义不由作者的意图担保；作者的死是读者的生",
  alias=["作者之死", "La mort de l'auteur", "作者功能", "作者不是意义的来源",
         "谁在说话有什么关系", "文本脱离作者独立运转"],
  src=dict(author="Roland Barthes", title="La mort de l'auteur", year=1967),
  also=[dict(author="Michel Foucault", title="Qu'est-ce qu'un auteur?", year=1969)],
  holds="任何「作者对自己产物的权威被解除」的判断",
  sep=["巴特是读者侧的事后宣告，是一种阅读伦理；福柯的作者功能是话语的分类装置",
       "若候选是作者侧的事前建造（思想者在封装的同时亲手预装解除通道），才有剩余"],
  verify="verified", frm="高鹏《自主松解》未切（该篇已由并发线发布，补切待办）"),

 dict(id="nbr-0030", ring="社会学",
  prop="卡里斯玛为延续自身而制度化，在制度化的过程中恰恰失去卡里斯玛",
  alias=["卡里斯玛的例行化", "Veralltäglichung", "routinization of charisma",
         "为延续而建制、建制反噬所延续之物", "创教者之后的教会"],
  src=dict(author="Max Weber", title="Wirtschaft und Gesellschaft", year=1922, zh="经济与社会"),
  holds="任何「为守护某物而建的制度反过来杀死该物」的判断",
  sep=["韦伯的例行化是一次性的历史转变，重心在权威类型的转换与继承问题",
       "若候选主张递归（每一次守护都更深地用程序模拟替换发生，且批判也是加速器），才有剩余"],
  verify="verified", frm="高鹏《递归性失活》未切（该篇已由并发线发布，补切待办）"),

 dict(id="nbr-0031", ring="行动哲学",
  prop="有些事我不能做——不是被禁止，而是做了就不再是我；意志的必然性划出人格的边界",
  alias=["volitional necessity", "意志的必然性", "我不能这么做", "在乎之物构成自我",
         "强评价", "底线跨过去就不再是自己"],
  src=dict(author="Harry G. Frankfurt", title="The Importance of What We Care About", year=1988),
  also=[dict(author="Charles Taylor", title="What is Human Agency?", year=1977)],
  holds="任何「自我认同的不可跨越点」类型的判断",
  sep=["法兰克福的必然性来自在乎结构（caring）的层级，是一种意志的构成，不依赖任何外部支撑的失效",
       "若候选要求一切外部支撑失效之后才显露出来（在无观众处仍起作用），才有剩余"],
  verify="verified", frm="高鹏《品核》未切（该篇已由并发线发布，补切待办）"),

 dict(id="nbr-0032", ring="组织社会学",
  prop="偏差被一点点重新定义为可接受，当事人对这场发生在自己内部的漂移毫无察觉",
  alias=["偏差的正常化", "normalization of deviance", "挑战者号", "一次次小让步累积成灾难",
         "标准被悄悄挪动而无人察觉"],
  src=dict(author="Diane Vaughan", title="The Challenger Launch Decision", year=1996),
  holds="任何「自我定义在不自觉中被逐步改写」的判断",
  sep=["范恩的漂移由组织的生产压力与文化脚本驱动，重心在决策共同体如何重新划定可接受风险",
       "若候选主张的是伦理自我在压力下的反向生成（不只是标准被挪动，而是我是谁被改写），须说明为何不能被文化脚本吸收"],
  verify="verified", frm="高鹏《反向雕刻》未切（该篇已由并发线发布，补切待办）"),

 dict(id="nbr-0033", ring="社会心理学",
  prop="做了不划算的事之后，人反而更相信它值得；努力本身生产确信",
  alias=["认知失调", "cognitive dissonance", "努力正当化", "effort justification",
         "不足理由效应", "付出之后理念获得重量", "入会仪式越苦越忠诚"],
  src=dict(author="Leon Festinger", title="A Theory of Cognitive Dissonance", year=1957),
  also=[dict(author="Aronson & Mills", title="The Effect of Severity of Initiation on Liking for a Group", year=1959)],
  holds="任何「行动之后信念获得强度」的判断",
  sep=["失调理论的机制是事后的态度调整以消除不一致，是心理层的、可逆的、可由旁观者复制",
       "若候选主张的是在不可逆的排他性动作中把重量当场写死（标定而非事后调整），才有剩余"],
  verify="verified", frm="高鹏《赋重》未切（该篇已由并发线发布，补切待办）"),

 dict(id="nbr-0034", ring="宗教心理学",
  prop="有一类人须经历一次剧烈的转折才获得新的自我，此前的自我被当众判死",
  alias=["二次诞生", "twice-born", "皈依", "conversion", "在理念中重生", "危机型转变"],
  src=dict(author="William James", title="The Varieties of Religious Experience", year=1902, zh="宗教经验种种"),
  holds="任何「新自我在绝境中与某个理念互相生成」的判断",
  sep=["詹姆斯的二次诞生以宗教对象的既存为前提：皈依者投向一个已经在那里的信仰",
       "若候选主张理念与自我互为助产士（理念本身也在这一刻才获得承载者），才有剩余"],
  verify="verified", frm="高鹏《在理念中诞生》未切（该篇已由并发线发布，补切待办）"),

 dict(id="nbr-0035", ring="风险治理",
  prop="风险认知通过信息与声誉的双重级联被社会性放大，最终与客观风险脱钩",
  alias=["可得性瀑布", "availability cascades", "风险的社会放大", "越讲越怕、越怕越讲",
         "级联式恐慌"],
  src=dict(author="Timur Kuran & Cass R. Sunstein", title="Availability Cascades and Risk Regulation", year=1999),
  holds="任何「信号密度抬高公众风险感知」的判断",
  sep=["瀑布的驱动源是分散的社会传播，没有任何行动者对级联负结构性责任",
       "若候选的驱动源是单一制度行动者的自我叙事义务（它是级联的稳定上游而非其中一个节点），才有剩余",
       "判据：只压低官方通报密度而社会传播照旧，瀑布理论预测风险感知不显著下降"],
  verify="verified", frm="高鹏《主权自限》补切"),

 dict(id="nbr-0036", ring="法社会学",
  prop="普通人与法律的关系有三种图式：在法律面前、与法律周旋、对抗法律；图式来自各自的处境与遭遇",
  alias=["法律意识", "legal consciousness", "before the law / with the law / against the law",
         "日常生活中的法", "普通人如何感知法律的在场"],
  src=dict(author="Patricia Ewick & Susan S. Silbey", title="The Common Place of Law", year=1998),
  holds="任何「公众对法律在场方式的感知」的判断",
  sep=["法律意识研究的自变量在公众侧：阶层、经验、遭遇史",
       "若候选的自变量在系统侧（信号向社会全域辐射、不经由个人遭遇），预测跨阶层收缩趋同，才有剩余"],
  verify="verified", frm="高鹏《主权自限》补切"),
]
