# -*- coding: utf-8 -*-
"""近邻库种子·D 批：由 /kb/placeholders.json 并入（2026-08-01）。

并库的理由写在 tools/merge_placeholder_cards.py 里：站上曾有两个近邻库，
schema 不同、消费者不同，而**两份判据分家一定会漂，且漂起来是静默的**。
现在只有这一处源，两个 json 都是它的投影。

⚠ pid 是这张卡在占位者库里的原 id（语义 slug），投影回 placeholders.json 时要原样用，
   否则碰撞机那边的引用会全部断掉。
"""

CARDS_D = [
 dict(id="nbr-0401", pid="control-variance-pathology", ring="生态学·制度",
  prop="以命令—控制压缩系统的自然变异范围，会使系统丧失韧性；且初期几乎总是成功的",
  alias=["压缩变异导致韧性丧失", "管理接管导致内生能力退化", "稳定化管理制造脆弱", "控制越强越脆", "初期成功掩盖长期崩溃", "command and control", "霍林", "梅菲", "命令与控制的病理"],
  src=dict(author="Holling & Meffe", title="Command and Control and the Pathology of Natural Resource Management", year=1996),
  holds="占住「外部持续管理→变异被压缩→韧性丧失」，且作者明写此病理同样适用于以命令—控制方式管理的机构",
  sep=["未占：最后一环归属（变异幅度 vs 结算权）、分期数作为独立于状态读数的变量"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0402", pid="automation-deskill-mask", ring="人因工程",
  prop="自动化接管控制后，手动技能不被使用即退化或从未生成；而自动化本身会遮蔽既有的能力退化，制造虚假安全感",
  alias=["接管控制导致技能不生成", "前段监测完好而后段被夺", "读数正常掩盖能力空缺", "出环问题", "监视者退化", "脱手", "ironies of automation", "out-of-the-loop", "班布里奇", "自动化的反讽"],
  src=dict(author="Bainbridge", title="Ironies of Automation", year=1983),
  holds="占住「断弧」：接管的是执行环，留给人的是监视环；且明写自动化会掩盖既有退化",
  sep=["未占：非人系统（生理/制度）的同构",
       "余额被系统自己承认这一条件"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0403", pid="ews-in-controlled-systems", ring="复杂系统·控制",
  prop="反馈受控系统趋近失稳仍可由临界慢化这类通用韧性指标监测到，无需系统模型",
  alias=["被控系统也有前兆", "控制系统的预警信号", "临界慢化在闭环里仍可测", "增量损伤直到小扰动才显形", "loss of control EWS"],
  src=dict(author="van Beers, Scheffer, Solanki, van de Leemput, van Nes, de Visser", title="Early warning signals for loss of control", year=2026),
  holds="直接反驳「被接管系统崩溃前无前兆」这类主张；无人机上已做出",
  sep=["反证条目：凡主张受控系统无预警者，须先与它交手"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0404", pid="stop-authority-in-hand", ring="生产管理",
  prop="把「停止」的决定权交给做事的人本身，是维持系统长期可运行的条件",
  alias=["停线权在内", "谁有权喊停", "停止生产以便生产永不停止", "结算权在内", "andon", "stop-work authority"],
  src=dict(author="Ohno 一脉·产业实践", title="Toyota Production System / Andon; Stop-Work Authority", year=1978),
  holds="占住「把停止权归还给内部」这一处方的实践形态",
  sep=["未占：为什么归还有效的机制说明",
       "它是做法不是理论"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0405", pid="legibility-destroys-metis", ring="政治人类学",
  prop="为使对象可读而施加的简化，在使其可治理的同时摧毁了那套地方性实践知识",
  alias=["可读性摧毁地方知识", "写下来即切割", "把默会做成可显现即损害", "国家的视角", "legibility", "metis", "斯科特", "可读性摧毁地方性知识"],
  src=dict(author="Scott", title="Seeing Like a State", year=1998),
  holds="占住「通货化即剥离」整条：解放成可援引＝可读化＝摧毁",
  sep=["未占：裁断动作与观看动作的分离（本文落点是裁断，那一支落点是看见）"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0406", pid="be-spontaneous-paradox", ring="沟通理论",
  prop="被命令去自发的行为不再是自发的；被授予的自主自我取消",
  alias=["留白不可被授予", "制度化的空窗自我取消", "命令你自由", "授权即取消", "双重束缚", "be spontaneous paradox", "瓦茨拉维克", "我命令你自发"],
  src=dict(author="Watzlawick, Beavin & Jackson", title="Pragmatics of Human Communication", year=1967),
  holds="占住「授权空窗悖论」全部",
  sep=["未占：资源与后果归属这一维",
       "可测量的后果（分期数）"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0407", pid="fragility-revealed-by-stressor", ring="风险论",
  prop="脆弱与稳健从外面看一样，只有压力事件才把它们分开；有些属性只在被扰动时显形",
  alias=["撤除才分得开", "不撤不可测", "压力显形", "反脆弱", "skin in the game", "antifragile", "塔勒布"],
  src=dict(author="Taleb", title="Antifragile; Skin in the Game", year=2012),
  holds="占住「暗处双态」的二值版本；Skin in the Game 另占「决策者须承担后果」",
  sep=["未占：第三态（现场组织出此前不存在的临时秩序）"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0408", pid="hermeneutical-injustice", ring="认识论",
  prop="缺乏共同的解释资源，使某些经验无法被理解与表达，因而无法被承认",
  alias=["没有语法所以说不出", "损失无法立案", "记不成一笔账", "诠释性不正义", "hermeneutical injustice", "弗里克"],
  src=dict(author="Fricker", title="Epistemic Injustice", year=2007),
  holds="占住「无账语法」整条",
  sep=["未占：记账科目缺失 vs 表达资源缺失（给了语汇仍不产生中间站）"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0409", pid="audit-society-reactivity", ring="组织社会学",
  prop="计量与排名一经公布即改变被计量者的行为；审计成为一种自我指涉的验证仪式",
  alias=["被测量者会变形", "指标反噬", "考核即塑形", "审计社会", "reactivity", "audit culture"],
  src=dict(author="Power 1997; Espeland & Sauder 2007", title="The Audit Society; Rankings and Reactivity", year=1997),
  holds="占住「显形税」的计量侧",
  sep=["未占：裁断权归属",
       "反应性讲的是被测者变形，不是余地不被生产"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0410", pid="classification-residue", ring="信息科学",
  prop="任何分类系统都生产它的残余，被归不进去的东西在制度上不存在",
  alias=["分类的残余", "没进科目就不存在", "无法被归类者", "sorting things out"],
  src=dict(author="Bowker & Star", title="Sorting Things Out", year=1999),
  holds="占住「未录即不存在」",
  sep=["未占：未生与未录的两级区分"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0411", pid="resilience-as-absorbable-quantity", ring="生态学",
  prop="韧性＝系统吸收扰动而不改变结构关系的量，与回到平衡点的速度是两回事",
  alias=["韧性是可吸收的扰动量", "缓冲存量", "适应性循环", "resilience", "panarchy"],
  src=dict(author="Holling", title="Resilience and Stability of Ecological Systems", year=1973),
  holds="占住「余地＝存量」这一读法",
  sep=["未占：余地＝动作留痕"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0412", pid="allostatic-load", ring="生理学",
  prop="长期过载下调节系统累积磨损，来源包括反复激活与无法适当关闭",
  alias=["磨损模型", "消退失败", "稳态应变负荷", "allostatic load"],
  src=dict(author="Sterling & Eyer 1988; McEwen 1998", title="Allostasis / Allostatic load", year=1988),
  holds="占住「余地＝未被磨损的完好度」",
  sep=["未占：从未被建成 vs 被磨损",
       "预后排序的反转"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0413", pid="good-regulator", ring="控制论",
  prop="任何好的调节器必然是被调节系统的一个模型",
  alias=["调节靠模型", "模型完备即可调节", "good regulator theorem"],
  src=dict(author="Conant & Ashby", title="Every good regulator of a system must be a model of that system", year=1970),
  holds="占住「调节能力依赖模型完备性」",
  sep=["未占：模型完备而裁断权外移时调节仍不发生"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0414", pid="decoupling-myth-ceremony", ring="组织社会学",
  prop="形式结构作为神话与仪式被采用，与实际运作脱耦，两套并行",
  alias=["形式与实质脱耦", "制度同构", "仪式性结构", "decoupling", "myth and ceremony"],
  src=dict(author="Meyer & Rowan", title="Institutionalized Organizations", year=1977),
  holds="占住「形式与实质分离」",
  sep=["未占：串联中断（一条回路后半段被挪走）"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0415", pid="critical-slowing-down", ring="复杂系统",
  prop="系统趋近临界点时出现自相关升高、方差增大、恢复变慢的通用前兆",
  alias=["临界慢化", "预警信号", "tipping point 前兆", "early warning signals", "谢弗"],
  src=dict(author="Scheffer et al.", title="Early-warning signals for critical transitions", year=2009),
  holds="占住「衰退有形状且可预警」",
  sep=["未占：无（本条已被 2026 扩展到受控系统，见 ews-in-controlled-systems）"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0416", pid="observer-blind-spot", ring="系统论",
  prop="划界者不能安置自己：观察的操作本身在它自己的视野里不可见",
  alias=["拇指不在指纹里", "规则不能规定自身应用", "元操作未被对象化", "反身性无穷后退", "操作自盲", "blind spot", "re-entry", "卢曼", "观察者盲点", "划界者不能安置自己"],
  src=dict(author="Spencer-Brown 1969; von Foerster; Luhmann", title="Laws of Form; Erkenntnis als Konstruktion; 社会系统理论", year=1969),
  holds="占住一切「划界者自身不可见」型命题",
  sep=["未占：须给出该盲点的可测代理"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0417", pid="masters-tools", ring="批判理论",
  prop="用压迫者的工具拆不掉压迫者的房子；反抗手段与被反抗结构同源",
  alias=["反抗工具与压迫同源", "收编先于反抗", "事前预装", "压抑性宽容", "master's tools"],
  src=dict(author="Lorde 1984; Marcuse 1965", title="The Master's Tools Will Never Dismantle the Master's House; Repressive Tolerance", year=1965),
  holds="占住「收编不在反抗之后而先行在场」的同向位置（不是对立派）",
  sep=["未占：事前/事后的时序判据须能读数"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0418", pid="recuperation-immunity", ring="社会理论",
  prop="批判被体制吸收并转化为其更新的养料；免疫过度即自体免疫",
  alias=["收编", "批判被吸收", "免疫式自噬", "recuperation", "immunitas", "autoimmunity"],
  src=dict(author="Boltanski & Chiapello 1999; Esposito 2002", title="Le nouvel esprit du capitalisme; Immunitas", year=1999),
  holds="占住「免疫式自噬」「假闭合」一族",
  sep=["未占：不可代偿的自我卷入判决"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0419", pid="participation-without-power", ring="规划学",
  prop="形式上参与而无实际决定权，阶梯低端的参与是安抚",
  alias=["有声无权", "形式参与", "参与阶梯", "ladder of participation", "阿恩斯坦"],
  src=dict(author="Arnstein", title="A Ladder of Citizen Participation", year=1969),
  holds="占住「前段有份、后段无权」的制度形态",
  sep=["未占：回路语言下的同构"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0420", pid="learned-helplessness", ring="心理学",
  prop="反复经历结果与行动无关，会导致主动应对本身停止发起",
  alias=["习得性无助", "后果回路断开", "做了也没用", "learned helplessness", "塞利格曼"],
  src=dict(author="Seligman & Maier", title="Failure to escape traumatic shock", year=1967),
  holds="占住「后果不回流→不再发起」",
  sep=["未占：能力从未生成 vs 发起被抑制"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0421", pid="job-characteristics-autonomy", ring="组织行为",
  prop="自主性、任务完整性与结果反馈是内在动机的结构条件",
  alias=["任务完整性", "结果反馈", "自主性", "job characteristics"],
  src=dict(author="Hackman & Oldham", title="Motivation through the design of work", year=1976),
  holds="占住「让人跑完全程」的动机学版本",
  sep=["未占：生理层与制度层的同构"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0422", pid="commons-self-governance", ring="制度经济学",
  prop="使用者自己制定、监督并执行规则的公共池塘资源可长期存续",
  alias=["自己定规则自己执行", "分级制裁", "内生规则", "polycentric", "governing the commons", "奥斯特罗姆", "公共池塘资源自治"],
  src=dict(author="Ostrom", title="Governing the Commons", year=1990),
  holds="占住「规则由内部制定与执行」的制度设计",
  sep=["未占：中间站的生产性"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0423", pid="exit-voice-loyalty", ring="政治经济学",
  prop="衰退中的组织，成员可退出或发声，二者的相对成本决定修复是否发生",
  alias=["退出与呼吁", "集体行动界面", "voice", "exit", "赫希曼"],
  src=dict(author="Hirschman", title="Exit, Voice, and Loyalty", year=1970),
  holds="占住「有没有一个可以开口的界面」",
  sep=["未占：开口之后留下的余额"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0424", pid="stability-breeds-instability", ring="宏观金融",
  prop="长期稳定本身孕育脆弱：平稳期使承担风险的结构逐步加杠杆",
  alias=["稳定制造不稳定", "平稳期积累脆弱", "金融不稳定假说", "Minsky moment", "明斯基", "稳定孕育不稳定"],
  src=dict(author="Minsky", title="The Financial Instability Hypothesis", year=1992),
  holds="占住「稳定期是脆弱的成因」",
  sep=["未占：机制（杠杆 vs 结算权）"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0425", pid="suppress-small-disturbance", ring="灾害学",
  prop="压制小规模扰动会积累出更大的灾难；防护工程反而抬高了暴露",
  alias=["小火不烧则大火", "堤坝效应", "安全发展悖论", "防护抬高暴露", "levee effect"],
  src=dict(author="White 1945 一脉", title="The levee effect / safe development paradox（火抑制与洪灾一族文献）", year=1945),
  holds="占住「不许小规模失败→断崖」这一条",
  sep=["未占：分期数作为可数变量"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0426", pid="experimenter-regress", ring="科学社会学",
  prop="判定仪器是否可靠须先知道正确结果，而正确结果又须靠仪器——检验陷入回归",
  alias=["实验者回归", "检验的循环", "没有独立判准", "experimenters regress"],
  src=dict(author="Collins", title="Changing Order", year=1985),
  holds="占住「检验手段与被检验对象互为前提」",
  sep=["未占：检测即致死这一代价维度"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0427", pid="tacit-knowing", ring="认识论",
  prop="我们知道的比我们能说出的多；默会知识不能被完整形式化",
  alias=["默会知识", "说不出的手感", "意会", "tacit knowledge", "波兰尼"],
  src=dict(author="Polanyi", title="The Tacit Dimension", year=1966),
  holds="占住「不可言说的那部分」",
  sep=["未占：它为何在制度里被降格为非存在"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0428", pid="developmental-systems", ring="生物学哲学",
  prop="生物性状不是预存程序的表达，而是在具体发展情境中实时建构的产物",
  alias=["不是预存程序", "性状是建构的", "发展系统论", "developmental systems theory", "niche construction"],
  src=dict(author="Oyama; Griffiths & Gray", title="Developmental Systems Theory / Cycles of Contingency", year=1985),
  holds="占住「调节秩序不是预存的」这一一般命题（胡敏原文已交代）",
  sep=["未占：外部干预剥夺生成条件的具体生理机制"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0429", pid="transaction-not-interaction", ring="实用主义",
  prop="有机体与环境不是两个可分离的实体在相互作用，而是同一事件的两面",
  alias=["不可分离性", "主客不可分", "交易而非互动", "transaction", "organism-environment"],
  src=dict(author="Dewey & Bentley", title="Knowing and the Known", year=1949),
  holds="占住「撤销可分离性预设」这一动作",
  sep=["未占：撤销之后的可裁决判据"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0430", pid="translation-obligatory-passage", ring="科学技术论",
  prop="利益经由转译被改写并汇聚到一个必经之点上",
  alias=["转译", "必经通道", "问题化—利益化—征召", "translation", "obligatory passage point"],
  src=dict(author="Callon", title="Some Elements of a Sociology of Translation", year=1986),
  holds="占住「转译」一词的来处（胡志英已交代）",
  sep=["未占：转译方向（催促→拖延）的机制"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0431", pid="goodharts-law", ring="公共管理",
  prop="一项指标一旦成为目标，就不再是好指标",
  alias=["指标变目标即失效", "考核即失真", "刷指标", "Goodhart's law", "Campbell's law", "古德哈特", "坎贝尔", "指标一旦成为目标就不再是好指标", "被评者预演判据", "为通过考核而重塑行为"],
  src=dict(author="Goodhart 1975; Campbell 1976", title="Goodhart's Law; Campbell's Law", year=1975),
  holds="占住「留痕一旦成为考核项即失效」",
  sep=["未占：留痕作为代理的失效条件之外的部分"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0432", pid="double-loop-learning", ring="组织学习",
  prop="只修正行动而不修正支配变量的学习是单环的；双环学习修改支配变量本身",
  alias=["单环双环", "事后修正支配变量", "double-loop learning"],
  src=dict(author="Argyris & Schön", title="Organizational Learning", year=1978),
  holds="占住「事后反思式修正」",
  sep=["未占：过程内部的证否（胡敏已划）"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0433", pid="normalization-of-deviance", ring="组织社会学",
  prop="偏差被逐次接受为正常，直到灾难；每一步在当时都可被辩护",
  alias=["偏差正常化", "每一步都合规", "温水", "normalization of deviance", "沃恩", "偏差的正常化"],
  src=dict(author="Vaughan", title="The Challenger Launch Decision", year=1996),
  holds="占住「一系列各自正确的决策叠加出崩溃」",
  sep=["未占：结算权归属这一变量"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0434", pid="radical-monopoly", ring="社会批判",
  prop="一种工具或服务的普及，会取消人们自己动手做同一件事的必要性，从而在不禁止任何人的情况下消灭那项能力",
  alias=["必要性被更便宜地满足", "不经拒绝而消失", "工具普及取消自为能力", "根本性垄断", "伊里奇", "无需禁止的剥夺", "radical monopoly"],
  src=dict(author="Illich", title="Tools for Conviviality", year=1973),
  holds="占住「不经过拒绝的消失」：不是压抑也不是剥夺执行条件，而是必要性被替代品接管",
  sep=["未占：可能性 vs 必要性的区分",
       "拒绝作为指纹唯一来源这一推论"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0435", pid="shifting-baselines", ring="渔业生态学",
  prop="每一代人把自己入行时见到的状态当作正常基线，于是长期退化被逐代重述为常态，退化本身不被察觉",
  alias=["基线偏移", "逐代重设正常值", "退化被重述为常态", "后来者把区分读成程度差", "波利", "shifting baseline"],
  src=dict(author="Pauly", title="Anecdotes and the shifting baseline syndrome of fisheries", year=1995),
  holds="占住「遗忘格」：区分消失后，后来者用程度差重述它",
  sep=["未占：长尾可被制度性场合人为拉长这一修正项"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0436", pid="intermediate-disturbance", ring="群落生态学",
  prop="多样性在中等强度的扰动下最高；扰动过少或过多都会使多样性下降",
  alias=["中度干扰假说", "扰动过少也有害", "断供深度差", "康奈尔", "intermediate disturbance"],
  src=dict(author="Connell", title="Diversity in tropical rain forests and coral reefs", year=1978),
  holds="占住「适度中断有益」这一整族说法的量的版本",
  sep=["未占：断的是种类而非量这一区分"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0437", pid="disruptive-innovation", ring="创新管理",
  prop="在位者按现有客户与利润池分配资源，因而系统性地看不见起初性能更差、后来颠覆市场的技术",
  alias=["破坏性创新", "在位者看不见", "资源分配流程的盲区", "克里斯坦森", "disruptive innovation"],
  src=dict(author="Christensen", title="The Innovator's Dilemma", year=1997),
  holds="占住「成功者的结构性失察」这一族的市场版本",
  sep=["未占：失察发生在必要性层而非需求层的情形"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0438", pid="generation-problem", ring="知识社会学",
  prop="社会变化不靠说服在世者完成，而靠新一代带着不同的成形经验进场、旧一代退场",
  alias=["代际问题", "靠换人不靠说服", "成形经验决定视野", "曼海姆", "problem of generations"],
  src=dict(author="Mannheim", title="Das Problem der Generationen", year=1928),
  holds="占住「区分随人退场而消失」的社会学解释",
  sep=["未占：能力仍在而必要性已无这一格"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0439", pid="care-receiving-responsiveness", ring="政治伦理学",
  prop="照料是一个四阶段过程，其最后一阶段是被照料者的回应；缺了这一阶段，照料在伦理上并未完成",
  alias=["照料的回应阶段", "被照料者的应答", "照料未完成", "特隆托", "care-receiving", "responsiveness"],
  src=dict(author="Tronto", title="Moral Boundaries: A Political Argument for an Ethic of Care", year=1993),
  holds="占住「照料需要回音才算结清」这一条",
  sep=["未占：回音缺席在照料者身上的生理沉淀",
       "由谁签回撤单"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0440", pid="mutual-recognition", ring="精神分析",
  prop="承认必须是相互的：把对方当作独立主体而非自我的延伸，双方才都能成为主体",
  alias=["相互承认", "主体间承认", "不把对方当延伸", "本雅明", "mutual recognition", "intersubjectivity"],
  src=dict(author="Benjamin", title="The Bonds of Love", year=1988),
  holds="占住「承认」这条路的全部正面表述",
  sep=["未占：被承认者被征用去为承认者签凭证这一反向结构"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0441", pid="parentification", ring="家庭治疗",
  prop="家庭中子女被置于照料父母的位置，承担了不属于其发展阶段的结算责任，形成隐性的关系账本",
  alias=["亲职化", "子女被征用为照料者", "隐性关系账本", "关系伦理", "博斯泽门伊-纳吉", "parentification", "invisible loyalties"],
  src=dict(author="Boszormenyi-Nagy & Spark", title="Invisible Loyalties", year=1973),
  holds="占住「关系里的账与代人受过」这一族",
  sep=["未占：签单人被撤下后是否在 6–12 个月内出现新签单人"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0442", pid="gift-obligation", ring="人类学",
  prop="礼物制造回赠的义务；给予、接受、回报三重义务构成社会纽带的基本形式",
  alias=["礼物之债", "回赠义务", "三重义务", "莫斯", "the gift", "reciprocity"],
  src=dict(author="Mauss", title="Essai sur le don", year=1925),
  holds="占住「给予产生债」这一族的全部经典表述",
  sep=["未占：债由谁来结、结不掉时沉淀在哪一层"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0443", pid="rules-vs-standards", ring="法经济学",
  prop="规则事前确定内容、标准事后确定内容；二者的取舍取决于制定成本与被规范者的预判成本如何分配",
  alias=["规则与标准", "事前确定还是事后确定", "可预判性的成本分配", "卡普洛", "rules versus standards", "判据在事前就能被推断", "被规范者能提前推断判据", "判据可预期"],
  src=dict(author="Kaplow", title="Rules versus Standards: An Economic Analysis", year=1992),
  holds="占住「判据在事前还是事后确定」这条轴",
  sep=["未占：可预期性与粗细/期限相互独立这一分离"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0444", pid="multitask-agency", ring="契约理论",
  prop="当任务的多个维度中只有一部分可测量时，对可测部分的激励会系统性地把努力从不可测部分抽走",
  alias=["多任务代理", "可测部分吸走努力", "激励扭曲配置", "霍姆斯特罗姆", "multitask principal-agent", "被评者向可测维度收敛", "努力向判据靠拢", "选题收敛"],
  src=dict(author="Holmström & Milgrom", title="Multitask Principal-Agent Analyses", year=1991),
  holds="占住「可测者挤出不可测者」这一族的形式化版本",
  sep=["未占：不必等任何一次测量发生即已收敛这一时序主张"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0445", pid="lottery-funding", ring="科研政策",
  prop="科研资助中引入随机抽签，用以对冲同行评议的保守偏好与评审噪声",
  alias=["抽签资助", "随机分配经费", "对冲评审保守", "不可预期的判据", "lottery funding", "random allocation", "判据不可提前推断", "让评审结果无法被预演", "选题收敛的解药"],
  src=dict(author="Osterloh & Frey 一脉·多家资助机构", title="Ranking games / partial randomisation in research funding（HRC 2013、VW『实验！』2017、FWF、SNSF）", year=2013),
  holds="占住「让判据不可预期」这一处方本身",
  sep=["未占：规则完全公开而结果仍不可预期（公开度与可预期性被分开）"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0446", pid="incentives-for-creativity", ring="劳动经济学",
  prop="容忍早期失败、给予长期视野的合约，比按短期里程碑考核更能产出突破性研究",
  alias=["容错激励", "长周期合约出创新", "赌人不赌题", "曼索", "incentives and creativity", "tolerance for failure", "短期里程碑考核使选题保守", "考核期限决定选题"],
  src=dict(author="Azoulay, Graff Zivin & Manso", title="Incentives and Creativity: Evidence from the Academic Life Sciences（NBER w15466）", year=2011),
  holds="占住「期限与容错」这条解释路径",
  sep=["未占：判据到动作的距离（三个月能学会写申请书，三个月变不成另一个人）"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0447", pid="still-face", ring="发展心理学",
  prop="照料者突然停止面部回应时，婴儿在数十秒内出现试探、抗议与退缩的固定序列",
  alias=["静脸实验", "停止回应引发退缩", "回音撤除的即时效应", "特罗尼克", "still face paradigm"],
  src=dict(author="Tronick et al.", title="The infant's response to entrapment between contradictory messages in face-to-face interaction", year=1978),
  holds="占住「回应撤除会立刻改变行为」这一实验范式",
  sep=["未占：成人版、以及撤除后由谁补签这一问"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0448", pid="ontological-insecurity", ring="精神病学",
  prop="当一个人的自我感须靠他人的确认来维持时，他人的定义就成为他存在的条件而非描述",
  alias=["存在性不安", "靠他人确认维持自我", "被定义即被安置", "莱恩", "ontological insecurity"],
  src=dict(author="Laing", title="The Divided Self / Self and Others", year=1960),
  holds="占住「被说成什么样就成了什么样」这一族",
  sep=["未占：这份确认是签给照料者而非签给自己"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0449", pid="adaptive-data-analysis", ring="机器学习",
  prop="对同一份数据反复提问，会使后续结论逐步过拟合；不可预期性随查询次数单调泄露",
  alias=["自适应数据分析", "反复查询导致泄露", "不可预期性会被磨掉", "更新率", "adaptive data analysis", "holdout reuse"],
  src=dict(author="Dwork, Feldman, Hardt, Pitassi, Reingold & Roth", title="Preserving Statistical Validity in Adaptive Data Analysis", year=2015),
  holds="占住「不可预期性不能一次造好、会随互动泄露」这一条",
  sep=["未占：把处方从「造不可预期的判据」退成「控制更新率」这一步"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0450", pid="goal-displacement", ring="组织社会学",
  prop="作为手段而设的规则与程序，会逐步变成目的本身；组织对规程的遵守取代了规程原本要服务的目标",
  alias=["目标置换", "手段变成目的", "为保障装置而运转", "规程压倒目标", "默顿", "goal displacement", "means-ends inversion"],
  src=dict(author="Merton", title="Bureaucratic Structure and Personality", year=1940),
  holds="占住「为保障 X 而建的装置成为必须被保障的东西」这一整族",
  sep=["未占：装置与被保障物之间的边界几何"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0451", pid="scale-mismatch", ring="社会生态系统",
  prop="资源被管理的空间或时间尺度，与它实际被供给的尺度不一致；许多管理失败源于这一错配而非管理不力",
  alias=["尺度错配", "管理尺度与过程尺度不一致", "在错误的边界上管理", "本地承载力不成立", "问题之适配", "康明", "scale mismatch", "problem of fit"],
  src=dict(author="Cumming, Cumming & Redman", title="Scale mismatches in social-ecological systems: causes, consequences, and solutions（Ecology and Society 11(1):14）", year=2006),
  holds="占住「那个量在管理边界上读不出」的整族说法，且文献已把承载力当作典型例子（驯鹿：官方视为定值、牧人视为随邻群与环境变动）",
  sep=["未占：从「读不准」推进到「在该边界内没有值」",
       "以及存量由路线而非由持有者定义"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0452", pid="entitlement-failure", ring="发展经济学",
  prop="饥荒常发生在粮食总量充足之时；决定生死的不是有没有粮，而是一个人有没有取得它的资格",
  alias=["权利失败", "取用资格", "粮在而取不到", "总量充足仍饥荒", "森", "entitlement approach", "exchange entitlement", "存量不在自己手里", "持有量为零不等于穷", "靠沿途取用", "能不能取到决定生死"],
  src=dict(author="Sen", title="Poverty and Famines: An Essay on Entitlement and Deprivation", year=1981),
  holds="占住「存量不在自己手里、能不能活取决于能不能取到」这一族的权利版本",
  sep=["未占：取用资格完好而通道被物理切断的情形（围栏化牧区）",
       "存量位置由路线定义这一几何"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0453", pid="tracking-variability", ring="旱地生态学",
  prop="在高变异干旱区，产量由降雨驱动而非放牧压力驱动；载畜量与承载力这类固定量不相干，流动性才是必需的应对，围栏与土地碎片化会削弱生产",
  alias=["非平衡牧场生态学", "追踪变异", "流动性是必需的", "载畜量不相干", "围栏削弱生产", "机会主义放牧", "non-equilibrium rangeland", "tracking variability", "储备寄存在别处", "靠走到那里才取得", "路线被切断即崩溃", "持有量低而路线多"],
  src=dict(author="Ellis & Swift 1988；Behnke & Scoones 1993；Vetter 2005；Briske et al. 2020", title="Range Ecology at Disequilibrium；Stability of African pastoral ecosystems", year=1988),
  holds="占住「别固定、跟着变异走」这一整条处方，并已指出补饲与定居化把牲畜与草场脱钩",
  sep=["未占：把流动性从管理策略重述为存量的定义"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0454", pid="storage-effect", ring="群落生态学",
  prop="环境波动下物种共存靠的是把好年景的收益储存起来度过坏年景；波动本身可以是共存的条件而非干扰",
  alias=["存储效应", "把好年景存下来", "波动支持共存", "切森", "storage effect", "把收益存起来度过坏年景", "储备的位置"],
  src=dict(author="Chesson", title="Multispecies competition in variable environments", year=1994),
  holds="占住「靠储存扛过波动」这一机制的时间版本",
  sep=["未占：储存在空间/路线上而非时间上",
       "持有量为零仍不穷"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0455", pid="campbell-law", ring="社会测量学 / 货币政策",
  prop="一个量化社会指标越是被用于社会决策，就越会腐蚀它本要监测的那个过程。",
  alias=["坎贝尔定律 / 古德哈特定律", "指标腐蚀", "测度变成目标", "Campbell's Law", "Goodhart's Law", "一考核就失真"],
  src=dict(author="Donald T. Campbell", title="Assessing the Impact of Planned Social Change", year=1979),
  holds="任何形如「一旦拿来考核就变形」「指标被优化后失去意义」的命题。",
  sep=["它的机制是目标化引发的博弈",
       "若你的机制在无人博弈、全员诚实时照样发生，才分得开。"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0456", pid="espeland-reactivity", ring="经济社会学 / 评价研究",
  prop="公共测度不是在描述社会世界，而是在重造它；被测者会朝指标重组自身。",
  alias=["反身性 (Reactivity)", "排名重造世界", "Rankings and Reactivity", "公共测度改变被测者"],
  src=dict(author="Wendy Espeland & Michael Sauder", title="Rankings and Reactivity: How Public Measures Recreate Social Worlds", year=2007),
  holds="任何形如「被评价者会朝评价标准改造自己」的命题。",
  sep=["它的时序是先测量后反应",
       "发生在测量之前的机制（预演）才与它可分。"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0457", pid="commensuration", ring="社会学",
  prop="把不可通约的东西译成一把共同的尺子本身是一种社会过程，且必须消灭大量信息。",
  alias=["可通约化 (Commensuration)", "把质变成量", "不可比变可比", "Commensuration as a Social Process"],
  src=dict(author="Wendy Espeland & Mitchell Stevens", title="Commensuration as a Social Process", year=1998),
  holds="任何形如「量化导致信息丢失／不同的东西被强行比较」的命题。",
  sep=["未占：本卡尚未写出分离线，用时须现补"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0458", pid="obligatory-passage", ring="科学技术论 (ANT)",
  prop="一个行动者若能把自己做成所有人达成目标都必须经过的位置，它就获得了定义什么算数的权力。",
  alias=["强制通行点 (Obligatory Passage Point)", "OPP", "转译社会学", "所有人都必须经过它", "Callon 扇贝"],
  src=dict(author="Michel Callon", title="Some Elements of a Sociology of Translation", year=1986),
  holds="任何形如「某个中介掌握了唯一通道因而掌握了定义权」的命题。",
  sep=["未占：本卡尚未写出分离线，用时须现补"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0459", pid="credibility-cycle", ring="科学社会学",
  prop="科学信用是一个可兑换循环：认可换资源、资源换数据、数据换文章、文章换认可。",
  alias=["可信度循环 (Credibility Cycle)", "实验室生活", "认可换资源", "科学信用是可兑换的"],
  src=dict(author="Bruno Latour & Steve Woolgar", title="Laboratory Life, ch.5", year=1979),
  holds="任何把学术承认写成货币、结算、兑换的命题。",
  sep=["未占：本卡尚未写出分离线，用时须现补"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0460", pid="organized-skepticism", ring="科学社会学",
  prop="制度化的相互质疑是科学的四条规范之一。",
  alias=["有组织的怀疑 (Organized Skepticism)", "CUDOS", "科学的规范结构", "制度化的相互质疑"],
  src=dict(author="Robert K. Merton", title="The Normative Structure of Science", year=1942),
  holds="任何形如「共同体应当互相拆台/互相质疑才健康」的命题。",
  sep=["它的对象是主张",
       "若你的对象是「某人不再提问这件事」，才分得开。"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0461", pid="isomorphism", ring="组织社会学",
  prop="同一场域里的组织会因强制、模仿与规范三种压力而趋同，与效率无关。",
  alias=["制度同构 (Institutional Isomorphism)", "铁笼再访", "组织趋同", "模仿性同构"],
  src=dict(author="Paul DiMaggio & Walter Powell", title="The Iron Cage Revisited", year=1983),
  holds="任何形如「同行越来越像」的命题。",
  sep=["未占：本卡尚未写出分离线，用时须现补"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0462", pid="rules-standards", ring="法经济学",
  prop="规则事前明确、遵从成本低但可被精确规避；标准事后裁量、抑制规避但当事人不知道自己是否合规。",
  alias=["规则与标准 (Rules vs Standards)", "事前明确 vs 事后裁量", "Kaplow", "合规可预期性"],
  src=dict(author="Louis Kaplow", title="Rules versus Standards: An Economic Analysis", year=1992),
  holds="任何以「可预期 / 不可预期」为轴的命题——它已经把这根轴形式化过。",
  sep=["它的关切是遵从与社会成本",
       "若你关切的是被规制者的问题集/创新形态，才分得开。"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0463", pid="motivating-innovation", ring="金融/契约理论",
  prop="要让代理人去探索，合同必须容忍早期失败并重赏长期成功。",
  alias=["探索的最优激励", "容错与长期", "Manso", "exploration vs exploitation 合同"],
  src=dict(author="Gustavo Manso", title="Motivating Innovation", year=2011),
  holds="任何形如「短周期考核扼杀创新」的命题。",
  sep=["它的变量只有期限与容错",
       "把这两项固定住仍能观察到差异，才分得开。"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0464", pid="hhmi-nih", ring="劳动经济学 / 科研政策",
  prop="长周期、容忍失败、以研究者为单位的资助，其产出的高影响力论文与新关键词都更多，低引用论文也更多。",
  alias=["以人为单位资助的实证", "HHMI vs NIH", "投人不投项目", "新颖度与失败品同时更多"],
  src=dict(author="Pierre Azoulay, Joshua Graff Zivin & Gustavo Manso", title="Incentives and Creativity: Evidence from the Academic Life Sciences", year=2011),
  holds="任何形如「宽松长周期的资助更有利于原创」的命题。",
  sep=["未占：本卡尚未写出分离线，用时须现补"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0465", pid="funding-lottery", ring="元科研 / 科研政策",
  prop="先由同行评议筛出够格的一批，再在其中随机抽取；理由是评审对边缘项目判别力弱、成本高、有偏见。",
  alias=["科研资助抽签", "部分随机化", "Explorer Grants", "Experiment!", "modified lottery", "抽签资助"],
  src=dict(author="Shahar Avin", title="Mavericks and Lotteries 等", year=2019),
  holds="任何主张「用随机替代部分评审」的命题。",
  sep=["它的理由是认识论与公平",
       "若你主张即使评审完美无偏、可预期的判据照样致害，才分得开。"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0466", pid="audit-culture", ring="人类学 / 会计学",
  prop="审计从核查手段变成治理文化，被审计者会为「可被审计」而重组自己的工作。",
  alias=["审计文化 (Audit Culture)", "为可审计性而重组", "Improving Ratings", "审计社会"],
  src=dict(author="Marilyn Strathern；Michael Power", title="'Improving Ratings': Audit in the British University System；The Audit Society", year=1997),
  holds="任何形如「为了应付检查而改变工作方式」的命题。",
  sep=["未占：本卡尚未写出分离线，用时须现补"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0467", pid="adaptive-overfit", ring="机器学习 / 统计",
  prop="隐藏的判据会随查询次数逐步泄露；公开基准被使用越久，榜上分数与真实能力的差距越大。",
  alias=["适应性数据分析的泄露", "private test set", "held-out 会被泄露", "reusable holdout", "榜单过拟合"],
  src=dict(author="Cynthia Dwork et al.；Benjamin Recht et al.", title="The Reusable Holdout；Do ImageNet Classifiers Generalize to ImageNet?", year=2015),
  holds="任何主张「把判据藏起来就能防优化」的命题——它会把这条改成一个有半衰期的量。",
  sep=["可以用它来给自己的命题加约束：不可预期性不是开关，是随交互单调衰减的量。"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0468", pid="surrogate-endpoint", ring="临床流行病学",
  prop="用中间指标代替最终结局会使整条研发管线朝那个指标对齐；抑制早搏的药物显著提高了死亡率。",
  alias=["替代终点 (Surrogate Endpoint)", "中间指标代替最终结局", "CAST 试验", "Prentice 判据"],
  src=dict(author="Ross Prentice；CAST Investigators；Fleming & DeMets", title="Surrogate Endpoints in Clinical Trials；CAST 1989", year=1989),
  holds="任何形如「优化了指标，结果更糟」的医学类兑现。",
  sep=["未占：本卡尚未写出分离线，用时须现补"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0469", pid="command-control", ring="生态学 / 资源管理",
  prop="为稳定产出而压缩系统的自然变异范围，短期几乎总是成功，长期使系统失去韧性；作者明写它同样适用于机构。",
  alias=["命令—控制的病理", "Holling & Meffe", "压缩变异导致韧性丧失", "command and control pathology"],
  src=dict(author="C. S. Holling & Gary Meffe", title="Command and Control and the Pathology of Natural Resource Management", year=1996),
  holds="任何形如「管理／接管导致内生能力丧失」的命题——这条在 1996 年就被占满六成。",
  sep=["未占：本卡尚未写出分离线，用时须现补"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0470", pid="shifting-baseline", ring="渔业生态学",
  prop="每一代把自己入行时看到的状态当作基线，于是长期退化在代际间不可见。",
  alias=["基线偏移 (Shifting Baseline Syndrome)", "Pauly", "每一代把退化后的状态当正常", "渔业基线"],
  src=dict(author="Daniel Pauly", title="Anecdotes and the Shifting Baseline Syndrome of Fisheries", year=1995),
  holds="任何形如「后来者不知道以前是什么样，于是把损失当成常态」的命题。",
  sep=["未占：本卡尚未写出分离线，用时须现补"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0471", pid="stop-work", ring="生产管理",
  prop="把「叫停」的权力交给现场的人，是为了让问题在当场被结算，而不是被推到下游。",
  alias=["停线权 (Andon / Stop-Work Authority)", "安灯绳", "停止生产以便永远不必停止", "丰田生产方式"],
  src=dict(author="Taiichi Ohno 一脉的现场实践", title="Toyota Production System", year=1978),
  holds="任何主张「把叫停权交还给内部人」的处方。",
  sep=["未占：本卡尚未写出分离线，用时须现补"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0472", pid="care-receiving", ring="政治伦理学",
  prop="照料不是给出即完成，被照料者的回应是判断照料是否成立的必要环节。",
  alias=["照料的第四阶段 (Care-receiving)", "Tronto", "responsiveness", "被照料者的回应是照料的完成"],
  src=dict(author="Joan Tronto", title="Moral Boundaries", year=1993),
  holds="任何形如「给予需要被回应才闭合」的命题。",
  sep=["未占：本卡尚未写出分离线，用时须现补"],
  verify="unverified", frm="占位者库并入"),

 dict(id="nbr-0473", pid="now-or-never-bottleneck", ring="认知科学·语言演化",
  prop="记忆转瞬即逝，语言输入必须当场被压缩与递交；这一瓶颈塑形了语言的处理、习得、演化与结构本身",
  alias=["当下或永不", "Now-or-Never bottleneck", "chunk-and-pass", "记忆瓶颈塑形语言", "克里斯蒂安森", "查特"],
  src=dict(author="Christiansen & Chater", title="The Now-or-Never Bottleneck: A Fundamental Constraint on Language", year=2016),
  holds="占住「语言结构由即时处理约束雕成」这一整族——凡把语言形态归给『来不及』的命题，先看它是不是这一条",
  sep=["未占：约束的来源是记忆容量还是**信道不可回头**（给足记忆但不许重播，约束是否仍在）",
       "可回放信道下的嵌套深度差异"],
  verify="verified", frm="占位者库并入"),

 dict(id="nbr-0474", pid="pdc-production-shapes-structure", ring="心理语言学",
  prop="记忆限制与组块是可变的，解释不了语言结构；结构更多来自产出端的难易在分布中被放大后回到理解端",
  alias=["Production-Distribution-Comprehension", "PDC", "产出难易塑形结构", "记忆限制解释不了结构", "麦克唐纳"],
  src=dict(author="MacDonald", title="Memory limitations and chunking are variable and cannot explain language structure（BBS 评论）", year=2016),
  holds="占住「对『瓶颈决定结构』的反驳位」：凡以处理约束解释结构的命题，都要先过她这一关",
  sep=["未占：把变量从『容量』换成『信道可回头性』之后，她的可变性反驳是否仍然成立"],
  verify="verified", frm="占位者库并入"),

]
