/* Node DOM/IndexedDB contract tests. This is not browser or real-model QA. */
const fs=require('fs'),vm=require('vm'),crypto=require('crypto'),assert=require('assert');
const {parseHTML}=require('linkedom');
const {indexedDB}=require('fake-indexeddb');
const path=require('path');const out=__dirname,root=path.resolve(__dirname,'../../public');
const {m,content,sha,collision}=JSON.parse(fs.readFileSync(out+'/runtime-fixture.json','utf8'));
const {window,document}=parseHTML('<!doctype html><html><head></head><body><main id="publication-unit"></main></body></html>');
window.indexedDB=indexedDB;window.PUBLICATION_UNIT={manifest:'/books/m/999/unit/learning.json',view:'agent'};
window.HTMLElement.prototype.scrollIntoView=function(){};window.HTMLElement.prototype.showModal=function(){this.open=true;};window.HTMLElement.prototype.close=function(){this.open=false;};
window.HTMLSelectElement.prototype.add=function(x){this.append(x);};Object.defineProperty(window.HTMLSelectElement.prototype,'value',{get(){return this._value??this.querySelector('option')?.value??'';},set(v){this._value=String(v);},configurable:true});
function Option(label,value){const e=document.createElement('option');e.textContent=label;e.value=String(value);return e;}
const location={origin:'http://localhost',href:'http://localhost/books/m/999/agent/',search:''};const history={replaceState(a,b,u){location.search=u;}};const requests=[];let corruptSource=false;
async function fetch(url,opts={}){url=String(url);if(url==='/api/wds/read'){requests.push(JSON.parse(opts.body));return new Response('data: '+JSON.stringify({t:'token',v:'模型建议：区分原文与推论。<script>不能执行</script>'})+'\n\ndata: {"t":"end"}\n\ndata: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}});}if(url.endsWith('/unit/learning.json'))return new Response(JSON.stringify(m));if(url.includes('/unit/sources/'))return new Response(JSON.stringify({title:'本章原文',url:'/books/m/999/chapter-1/',text:corruptSource?content+'被改写':content,sha256:sha}));throw Error('Unexpected fetch '+url);}
const sandbox={window,document,console,Option,location,history,crypto:crypto.webcrypto,fetch,Response,ReadableStream,TextDecoder,TextEncoder,Uint8Array,URL,URLSearchParams,Blob,AbortController,DOMException,setTimeout,clearTimeout,confirm:()=>true,navigator:{},BroadcastChannel:class{postMessage(){}},module:undefined};
const ctx=vm.createContext(sandbox);vm.runInContext(fs.readFileSync(root+'/books/unit-runtime/core.js','utf8'),ctx);vm.runInContext(fs.readFileSync(root+'/books/unit-runtime/app.js','utf8').replace('boot().catch(e=>', 'window.__unitTest={clearSourceCache:()=>sourceCache.clear(),getManifest:()=>manifest};boot().catch(e=>'),ctx);
const $=id=>document.getElementById(id),pause=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn){for(let i=0;i<100;i++){if(fn())return;await pause(10);}throw Error('Timeout; status='+$('status')?.textContent);}
async function click(id){await $(id).onclick({preventDefault(){}});await pause(10);}
(async()=>{await until(()=>$('workspace')&&!$('workspace').hidden&&$('loading').hidden);assert.equal($('chapter-select').children.length,2);assert.equal($('mode').value,'read');assert.equal($('agent-starts').children.length,5);assert($('source-text').textContent.includes('<script>'));assert.equal($('source-text').querySelectorAll('script').length,0);assert.equal(requests.length,0);assert($('overview').textContent.includes('快速进入'));assert(!$('capstone').hidden);assert($('answer-guide').textContent.includes('先定位原文'));
$('initial').value='我的初答：知识是已经完成的。';await click('save-initial');assert($('initial').disabled);$('reanswer').value='复答：需要解释互动条件。';await click('save-reanswer');$('revision').value='我确认区分原文与推论。';await click('save-revision');assert($('status').textContent.includes('勾选'));$('confirm-revision').checked=true;await click('save-revision');
await click('preview-btn');assert($('preview').open);let payload=JSON.parse($('payload').textContent);assert.equal(payload.bookNo,999);assert.equal(payload.sourceMode,'selected-original');assert(!payload.docText.includes('我的初答'));assert.equal(payload.history.length,0);$('api-key').value='TEST-KEY-NOT-REAL';$('cost-consent').checked=true;await click('send-confirmed');assert.equal(requests.length,1);assert($('status').textContent.includes('本轮建议已保留'));assert.equal($('api-key').value,'');
$('include-personal').checked=true;$('include-history').checked=true;$('include-collisions').checked=true;$('question').value='继续检验我的复答。';await click('preview-btn');payload=JSON.parse($('payload').textContent);assert(payload.docText.includes('我的初答'));assert.equal(payload.history.length,2);assert(payload.bookRag.includes(collision));await click('close-preview');
const C=window.PublicationUnitCore.create(m),a=await C.archive();assert(!JSON.stringify(a).includes('TEST-KEY-NOT-REAL'));await assert.rejects(()=>C.importArchive({...a,unitId:'m-998'}));const init=a.events.find(e=>e.type==='initial');await assert.rejects(()=>C.importArchive({...a,events:[{...init,id:crypto.randomUUID(),data:{text:'另一个初答'}}]}));assert.equal((await C.archive()).events.length,a.events.length);const partial=await window.PublicationUnitCore.parseSSE(new Response('data: {"t":"token","v":"片段"}\n\n'),()=>{});assert.equal(partial,'interrupted');const broken=await window.PublicationUnitCore.parseSSE(new Response('data: {broken}\n\ndata: {"t":"end"}\n\ndata: [DONE]\n\n'),()=>{});assert.equal(broken,'interrupted');
$('chapter-select').value='2';await $('chapter-select').onchange();await until(()=>$('task-number').textContent.startsWith('02'));assert.equal($('initial').value,'');assert(!$('include-history').checked);$('chapter-select').value='1';await $('chapter-select').onchange();await until(()=>$('initial').disabled);assert.equal($('initial').value,'我的初答：知识是已经完成的。');
await C.importArchive({...a,events:[],drafts:[{id:'fields:1',book:'m-999',lesson:1,fields:{reanswer:'导入的另一份复答'}}]});assert((await C.read('drafts')).some(d=>d.id.startsWith('import:')&&d.fields.reanswer==='导入的另一份复答'));
// Gate prompts locate the first cited chapter in Arabic and Chinese forms.
const liveManifest=window.__unitTest.getManifest(),originalRead=liveManifest.agent.starts.read;
liveManifest.agent.starts.read='请依据第二章解释概念。';await $('agent-starts').children[0].onclick();assert($('task-number').textContent.startsWith('02'));
liveManifest.agent.starts.read='请依据第1章说明。';await $('agent-starts').children[0].onclick();assert($('task-number').textContent.startsWith('01'));
liveManifest.agent.starts.read='这本书的总体方法是什么？';await $('agent-starts').children[0].onclick();assert($('status').textContent.includes('不会自动把全书'));
liveManifest.agent.starts.read=originalRead;
// Failure paths use controlled mocks; nothing is sent on failed previews.
const callsBefore=requests.length;$('question').value='x'.repeat(4100);await click('preview-btn');assert($('status').textContent.includes('4000'));assert.equal(requests.length,callsBefore);$('question').value='正常问题';await click('preview-btn');$('question').value='预览之后被改写';$('api-key').value='TEST-KEY-NOT-REAL';$('cost-consent').checked=true;await click('send-confirmed');assert($('status').textContent.includes('已经变化'));assert.equal(requests.length,callsBefore);await click('close-preview');
// Corrupted source response cannot be used for a model request.
window.__unitTest.clearSourceCache();corruptSource=true;$('chapter-select').value='2';await $('chapter-select').onchange();assert($('status').textContent.includes('校验不一致'));assert($('preview-btn').disabled);assert.equal(requests.length,callsBefore);corruptSource=false;await $('chapter-select').onchange();assert(!$('preview-btn').disabled);
// Invalid optional cross-book URL disables comparison inclusion, preserving valid reading.
window.__unitTest.getManifest().tasks[0].collisions[0].url='javascript:alert(1)';$('chapter-select').value='1';await $('chapter-select').onchange();assert($('include-collisions').disabled);assert(!$('preview-btn').disabled);assert($('collision-sources').textContent.includes('链接无效'));
// Failed persistent storage is represented through an IndexedDB provider that always errors.
const brokenRoot={crypto:crypto.webcrypto,indexedDB:{open(){const request={};setTimeout(()=>{request.error=new Error('quota unavailable');request.onerror?.();},0);return request;}}};const brokenCtx=vm.createContext({window:brokenRoot,console,TextDecoder,TextEncoder,Response,DOMException,Uint8Array,setTimeout});vm.runInContext(fs.readFileSync(root+'/books/unit-runtime/core.js','utf8'),brokenCtx);const brokenC=brokenRoot.PublicationUnitCore.create(m);await assert.rejects(()=>brokenC.append(brokenC.event(1,'initial',{text:'应保留的初答'},null)),/quota unavailable/);
const tests=['dynamic-task-navigation','agent-default-read-and-five-gates','overview-routes-capstone-answer-guide','source-hash-and-safe-text-rendering','no-automatic-model-call','initial-sealed','revision-confirmation-required','preview-personal-default-off','real-endpoint-request-shape-with-mocked-sse','same-task-history-opt-in','collision-opt-in','key-excluded-from-archive','cross-book-import-rejected','atomic-initial-conflict-rejected','partial-and-malformed-stream-not-complete','chapter-record-isolation','imported-conflicting-draft-preserved','overlength-question-rejected-without-call','preview-change-rejected-without-call','unavailable-indexeddb-reported','tampered-source-hash-blocks-request','invalid-comparison-url-isolated-from-valid-reading','starter-arabic-chapter-location','starter-chinese-chapter-location','global-concept-question-keeps-explicit-source-scope'];
const report={passed:true,environment:'Node VM + linkedom + fake-indexeddb; simulated DOM/IndexedDB and SSE, not browser QA',checks:tests,records:a.events.length,modelCallsMocked:requests.length,realModelTested:false,browserTested:false};fs.writeFileSync(out+'/runtime-qa-result.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));process.exit(0);})().catch(e=>{console.error(e.stack);console.error('STATUS',$('status')?.textContent);process.exit(1);});
