# -*- coding: utf-8 -*-
"""三视角图册数据：篇目 · 图名（原册目录）· 附录《文章视频搜索》· 二维码解出的原文链接。

   由 tools/mkthreeviews.py 读取。数据源＝《三视角图册》PDF（200 页）：
     SECTIONS/NAMES 抄自原册目录（页 2–6），APPENDIX 抄自原册附录（页 148–153），
     QR 由 pyzbar 逐页解码正文 140 图（原册页 8–147）得来。
   ⚠ 补遗 47 图（原册页 154–200）上那 39 枚二维码全是同一枚个人微信名片码，
     不入库、不上站；导出图片时已用白块遮掉。
"""

XQR_REMOVED = 39

# (中文篇名, slug, 起始图号, 结束图号)
SECTIONS = [
    ('智慧论', 'wisdom', 1, 6),
    ('本体论', 'ontology', 7, 12),
    ('发展论', 'development', 13, 19),
    ('价值论', 'value', 20, 22),
    ('神学篇', 'theology', 23, 33),
    ('科学篇', 'science', 34, 40),
    ('哲学篇', 'philosophy', 41, 44),
    ('国学·道学篇', 'guoxue', 45, 51),
    ('佛学篇', 'buddhism', 52, 52),
    ('知识论篇', 'epistemology', 53, 58),
    ('教育学篇', 'education', 59, 64),
    ('学习篇', 'learning', 65, 74),
    ('经济学篇', 'economics', 75, 79),
    ('管理·事业篇', 'management', 80, 85),
    ('创新篇', 'innovation', 86, 90),
    ('逻辑学篇', 'logic', 91, 97),
    ('生命体篇', 'life-body', 98, 111),
    ('人生篇', 'life', 112, 124),
    ('生理健康篇', 'health', 125, 135),
    ('美学篇', 'aesthetics', 136, 140),
]

# 图号 -> 图名（原册目录）
NAMES = {
    1: '321智慧',
    2: '智慧27宫格',
    3: '智慧81宫格',
    4: '三视角智慧',
    5: '智慧三合一通融',
    6: '智慧四合一通融',
    7: '二元本体论',
    8: '规范九宫格',
    9: '规范27宫格',
    10: '本体论九宫格',
    11: '本体论27宫格',
    12: '本体论19683',
    13: '三视角方法论',
    14: '实践27宫格',
    15: '问题解决27宫格',
    16: '123原理',
    17: '发展论27宫格',
    18: '三视角发展之经',
    19: '三视角类比通融',
    20: '价值论27宫格',
    21: '价值需求',
    22: '智慧附体价值论',
    23: '三视角',
    24: '三一神',
    25: '神符号学',
    26: '美好团契',
    27: '321神论',
    28: '三一神九宫格',
    29: '基督九宫格',
    30: '主耶稣',
    31: '十诫',
    32: '罪人',
    33: '圣经世界观',
    34: '科学九宫格',
    35: '自然科学',
    36: '物理学九宫格',
    37: '种群学',
    38: '天',
    39: '大自然九宫格',
    40: '大自然与生理',
    41: '哲学九宫格',
    42: '得福大智慧',
    43: '存在论27宫格',
    44: '模型九宫格',
    45: '国学',
    46: '华人三本书',
    47: '道德经九宫格',
    48: '易经九宫格',
    49: '元亨利贞',
    50: '儒家九宫格',
    51: '君子九宫格',
    52: '佛教九宫格',
    53: '人类知识九宫格体系',
    54: '知识九宫格',
    55: '知识论27宫格',
    56: '知识论81宫格',
    57: '321个人文明生产机',
    58: '知识生产机',
    59: '教育27宫格',
    60: '教育81宫格',
    61: '教学效果',
    62: '自由九宫格',
    63: '学校教育三视角',
    64: '真人',
    65: '训而达九宫格',
    66: '学习27宫格',
    67: '思维九宫格',
    68: '思维27宫格',
    69: '读书九宫格',
    70: '读书27宫格',
    71: '如何高效学习',
    72: '用身认知',
    73: '数学本体论九宫格',
    74: '计算机九宫格',
    75: '市场营销',
    76: '市场营销九宫格',
    77: '21世纪中国经济',
    78: '21世纪企业转型',
    79: '贫穷三视角',
    80: '基于国学的企业管理',
    81: '领导九宫格',
    82: '人力资源管理',
    83: '事业模式',
    84: '事业模式27宫格',
    85: '事业晕痛苦',
    86: '创造力三大门',
    87: '创新实践',
    88: '创新27宫格',
    89: '创新81宫格',
    90: '学科通融创新',
    91: '三大推理',
    92: '逻辑九宫格',
    93: '逻辑大风车',
    94: '类比九宫格',
    95: '形式逻辑27宫格',
    96: '处境逻辑',
    97: '三一逻辑27宫格',
    98: '三视角智慧生命体',
    99: '生命体27宫格',
    100: '人生的三世界',
    101: '生命（管理）81宫格',
    102: '人的九宫格',
    103: '人的81宫格',
    104: '人格九宫格',
    105: '人格27宫格',
    106: '心27宫格',
    107: '心81宫格',
    108: 'Mind心智27宫格',
    109: '精神27宫格',
    110: '心理学本体论27宫格',
    111: 'Mind心智',
    112: '爱的九宫格',
    113: '个人的信望爱',
    114: '幸福九宫格',
    115: '幸福的人生',
    116: '人生受罪九宫格',
    117: '心有灵犀',
    118: '生命本体论',
    119: '生活本体论',
    120: '生存本体论',
    121: '生命智慧27宫格',
    122: '生活智慧27宫格',
    123: '生存智慧27宫格',
    124: '321认知',
    125: '中医养生保健',
    126: '生理九大系统',
    127: '生理系统与处境通融',
    128: '生理通融',
    129: '生理通融II',
    130: '生理27宫格',
    131: '癌症',
    132: '癌细胞九宫格',
    133: '癌细胞与罪人通融',
    134: '人的健康',
    135: '三一健身',
    136: '美学艺术',
    137: '美的27宫格',
    138: '绘画艺术九宫格',
    139: '视觉规范九宫格',
    140: '三色图',
}

# 图号 -> 原册附录列出的原文/视频标题
APPENDIX = {
    1: ['三视角入门：对比、变化、分布', '321智慧是什么？'],
    2: ['三视角智慧应用模式123'],
    3: ['何为人生智慧？', '如何应用三视角理论解构别人理论体系'],
    4: ['如何学习三视角智慧呢？', '三元论与三视角', '三视角入门九宫格细解（视频）'],
    5: ['多视角「思维」的美好梦想'],
    6: ['怎样走入三视角智慧的殿堂'],
    7: ['二元思维入门课程（附视频）', '二元论给人类带来的危害', '二元思维是如何导致愚昧无知的呢？'],
    8: ['三视角九灯图格物致知', '对比变化分布的彼此包含关系', '三视角和第一原理之源头（视频）'],
    9: ['本体论新解构和应用', '超越维特根斯坦', '论点，论据，论证是皇帝的新装'],
    10: ['三视角九宫格入门', '如何去执、开悟、破境？', '本体论之美（视频）'],
    11: ['为什么没有所谓的事物固有属性？', '分割和还原就是客观事实吗？', '分布视角的预设和我们的忽视'],
    12: ['如何建造创造力生命的DNA？', '三视角、九宫格、27宫格（视频）'],
    13: ['人人都在吸的精神鸦片'],
    14: ['法术器的三视角解析'],
    15: ['你想获得创新的方法吗？'],
    16: ['123原理奥秘初探', '如何应用123原理', '123原理剖析本体论27宫格'],
    17: ['在二元对立矛盾处理中建立创造力'],
    18: ['从易经蒙卦看启蒙的原则', '以不变应万变'],
    19: ['创造力三密码大公开'],
    20: ['你每天那么忙，生活有改变吗？'],
    21: ['为何你的人生如此晕痛苦呢？'],
    22: ['你真的懂「成功与失败」吗？'],
    23: ['如何从圣经悟营销'],
    24: ['从圣经到三视角应用'],
    25: ['从圣经到三视角', '皮尔斯的三范畴和三视角符号学'],
    26: ['大爱带来至高喜乐', '人生影响取决心态'],
    27: ['正面管教的三视角解构入门'],
    28: ['从圣经学习顾客签单5步曲'],
    29: ['从圣经学营销'],
    30: ['三视角逆龄大健康学员见证大集合'],
    31: ['你的心在哪儿呢？'],
    32: ['为何依靠自己会带来愚昧呢？'],
    33: ['概念思维的罪性', '概念：思维的囚牢（视频）'],
    34: ['正在让孩子学习超能力的家长一定注意了'],
    35: ['不仅仅是活着'],
    36: ['三视角物理学智慧入门及应用'],
    37: ['你的孩子知道如何学习吗？'],
    38: ['如何活在当下'],
    39: ['读书，读人，还要读大自然'],
    40: ['胰岛素阻抗三视角解读'],
    41: ['先有鸡还是先有蛋'],
    42: ['舍得大智慧解密'],
    43: ['如何高效做事？'],
    44: ['从粒子波场三个视角认识事物'],
    45: ['当今国学智慧课程的四大错误', '国学学习感悟'],
    46: ['从天地人合一看三视角智慧的习得和应用', '明心见性'],
    47: ['从三视角看道德经的智慧', '道和逻辑'],
    48: ['易经阴阳智慧大解构', '潜龙勿用！'],
    49: ['略论中国古典美学'],
    50: ['从天地人合一看三视角智慧', '孔子的教学智慧'],
    51: ['论语开篇三视角解读'],
    52: ['三视角智慧让你看得更远、更广、更早'],
    53: ['人类知识体系9宫格'],
    54: ['视角思维成为新加坡大学教育内容', '三视角中阶课程层级理论入门', '如何应用三视角写好一篇作文？'],
    55: ['孩子和成人谁更能主动学习呢？', '一个人很有文化是什么意思？'],
    56: ['孩子只学自己喜欢的学科怎么办？', '辅导作业再也不需要「找亲家」了'],
    59: ['三视角教育', '三视角教学法', '古典教育真的那么好吗？'],
    60: ['教育是什么？', '写给在教育内卷中焦虑重重的家长', '这样的娃可咋整'],
    61: ['你想知道教学和推销的智慧吗？', '考试高分九宫格智慧'],
    62: ['谁是利己主义者的培养祸首？', '无用之用，方为大用！', '打卡的危害'],
    63: ['从三个视角来看学校', '德鲁克谈学校的创新和管理', '如何引导孩子自主学习'],
    64: ['创造力成长的奥秘'],
    65: ['意志教育三视角', '为什么外国大师辈出呢？'],
    66: ['为何越学习越晕头转向', '学习到底学什么？怎么学？', '三视角语言学入门'],
    67: ['你想学会画思维导图吗？', '思维导图的毒素是什么呢？'],
    68: ['破除对三大逻辑推理的迷信', '三大逻辑律彰显人类的愚昧无知'],
    69: ['如何高效读书？'],
    70: ['如何高效阅读？', '高效记忆的秘密'],
    71: ['如何智慧地学习汉字？', '学单词还需要死记硬背吗？', '如何学词根和单词'],
    72: ['具身认知入门'],
    73: ['数学是什么？', '数学逻辑的革命：从圆的定义谈起', '如何正确启蒙孩子数学'],
    74: ['三视角刷题'],
    75: ['商业如何做？', '为何对方就是不买单？'],
    76: ['市场营销和商品推销是一码事吗？'],
    77: ['何谓刚强？何谓软弱呢？'],
    78: ['如何创立一家成功的21世纪的企业'],
    79: ['脱离贫穷的奥秘是什么？'],
    80: ['喜欢学习一定是好事吗？'],
    81: ['企业家的商业艺术'],
    82: ['创造性发现人力资源管理九宫格'],
    83: ['三视角管理', '用户思维的三视角解析'],
    84: ['商业模式细解', '职场内卷和出路'],
    85: ['如何发现顾客的痛点？'],
    86: ['如何创新'],
    87: ['普通大学生如何达到博士的水平？'],
    88: ['创造力强大的奥秘'],
    89: ['如何快速学会水平思考，开启创造力？'],
    90: ['万剑穿心'],
    91: ['三视角发展简史', '三大推理之类比、演绎、归纳'],
    92: ['亚父的逻辑学给人类带来的是福音还是灾难？'],
    93: ['按逻辑律做事业，为何会颗粒无收呢？'],
    94: ['类比九宫格（视频）'],
    95: ['形式逻辑的方向指导'],
    96: ['三一逻辑是人类理性重生的利器'],
    97: ['三一逻辑的进一步解构', '从模式的视角看三一逻辑'],
    98: ['三视角是时代的需要', '如何管教孩子？'],
    99: ['到底心身灵大健康是什么呢？', '习惯是死亡之母'],
    100: ['人生三世界'],
    101: ['如何减少个人心理及组织的内耗？'],
    102: ['认识自己是幸福的入门', '对事不对人是皇帝的新装'],
    103: ['你想获得自信吗？要小心！'],
    104: ['当文艺遇见科技'],
    105: ['创造力的DNA奥秘'],
    106: ['如何找到自己的人生使命？', '如何清晰自己的使命？'],
    107: ['成长型心态和思维到底是什么呢？', '成长，成长，再成长', '成长心态继续聊'],
    108: ['知情意三大健康的互相影响', '如何成为一个情商高的人？'],
    109: ['现在抑郁症是一种流行病'],
    110: ['三视角心理健康入门', '如何调整不良情绪', '三视角解构「意识」和「潜意识」'],
    111: ['真的完全客观，与人无关？', '你想拥有直觉的智慧吗？'],
    112: ['三视角智慧美好的见证'],
    113: ['哪有什么自爱自尊自信？'],
    114: ['易经的交易和人的舍己'],
    115: ['幸福人生的奥秘解构'],
    116: ['人生痛苦三视角'],
    117: ['归回起初之爱'],
    118: ['你想变得幽默吗？', '幽默引你走向智慧人生'],
    119: ['如何做到低成本，高收入呢？'],
    120: ['三视角解构内卷的奥秘'],
    125: ['何谓三视角逆龄大健康？'],
    126: ['生理九宫格入门', '奇妙的人体三大调节系统', '高血压治疗（视频）'],
    127: ['人体九大生理系统互相有何关系？', '三视角大健康'],
    128: ['何谓健康的饮食习惯？', '饮食智慧三视角（视频）'],
    129: ['蛋白质脂肪糖代谢入门'],
    130: ['认识身体', '对付新冠病毒：提升免疫力'],
    131: ['如何治疗我们的思维癌症呢？', '思维和认知癌症（视频）'],
    132: ['癌症治疗九宫格（视频）'],
    133: ['自信的再剖析'],
    134: ['三视角心身灵大健康入门', '何谓逆龄大健康（视频）'],
    135: ['何谓年轻和健康？', '三视角逆龄大健康学员断食分享'],
    136: ['漫谈美和艺术', '美的形式三视角（有声）'],
    137: ['什么是美'],
    138: ['为什么梵高的画那么值钱？', '为何很多艺术家好像都有一些疯癫？'],
    139: ['印象派绘画入门（视频）'],
}

# 图号 -> 该页二维码解出的链接（微信公众号原文/视频）
QR = {
    1: ['https://mp.weixin.qq.com/s/yQCCP75vJKdr4vzX9NPoNA', 'https://mp.weixin.qq.com/s/z3WEfAXMIPf2xnFmdokcHQ', 'https://mp.weixin.qq.com/s/cpD2DFOIh2tf-Hh7jdKcqw', 'https://mp.weixin.qq.com/s/Cw8FFrcnK9pQah9o9QV4cg'],
    2: ['https://mp.weixin.qq.com/s/aHstlGI2dLRDYBiamPwhnA', 'https://mp.weixin.qq.com/s/khVg5WaxBSIawXhhlcU73A', 'https://mp.weixin.qq.com/s/b0vNkGQ9vvqzMG-F_qsQiQ'],
    3: ['https://mp.weixin.qq.com/s/xMgsStjWBUHPkItckRxwuw', 'https://mp.weixin.qq.com/s/JCz_EXYoS7kFs5nidPfAmQ'],
    4: ['https://mp.weixin.qq.com/s/aW_gFrIs-kCkHi7zJxL7fw', 'https://mp.weixin.qq.com/s/6OdwKzTCWmYA6O3NMdFm1Q'],
    5: ['https://mp.weixin.qq.com/s/isGz67TfEWYiqNbOycAZnA'],
    6: ['https://mp.weixin.qq.com/s/ofkxbsXlKXD8yPKP0yMyeA'],
    7: ['https://mp.weixin.qq.com/s/IdOGhtNlahdnIHt_eD1YMw', 'https://mp.weixin.qq.com/s/wDblwxjvvXDOgvPfYid7Rw', 'https://mp.weixin.qq.com/s/L55haA8QbLLNOpQnaivlPg'],
    8: ['https://mp.weixin.qq.com/s/BWuekq_YrJH2RbhQnBc_bQ', 'https://mp.weixin.qq.com/s/o-J2J1aGnThJA2D-wW8-gg'],
    9: ['https://mp.weixin.qq.com/s/eyeI7us9bncgceDaecXNqw', 'https://mp.weixin.qq.com/s/1agLM4PLIU3wOUzgXLq5RQ', 'https://mp.weixin.qq.com/s/NZ3vy1njWY9ySH5mx4F_6g'],
    10: ['https://mp.weixin.qq.com/s/XUJDKbFc5aoHTl5HfYe72A', 'https://mp.weixin.qq.com/s/qLAMbsd7R6bY1MMhU8TqJQ'],
    11: ['https://mp.weixin.qq.com/s/IFYIdURQbLxpEcJaQ2F2WA', 'https://mp.weixin.qq.com/s/vvq0VJbXbIrzcBTjTNhvTQ', 'https://mp.weixin.qq.com/s/7Ilg5SUkWGpRFNS3AUgCSg'],
    12: ['https://mp.weixin.qq.com/s/t4dbAzd5162liH0WgzQF4g'],
    13: ['https://mp.weixin.qq.com/s/IRj8j5-o-WzirQgl0rHnPg'],
    14: ['https://mp.weixin.qq.com/s/WP1XhMRPQb4fDLCiFtF5IQ'],
    15: ['https://mp.weixin.qq.com/s/93ZgO49CeYJcD40m6PVRKA'],
    16: ['https://mp.weixin.qq.com/s/d2rX8o_9p7xUSDd0oJdN3A', 'https://mp.weixin.qq.com/s/Vd3X9G5kPCiRH-KRrigjvA', 'https://mp.weixin.qq.com/s/Tb1H1C0jF2TYGXU-UuQ71g'],
    17: ['https://mp.weixin.qq.com/s/xpjqZKS7BzdNXa98eLg6Qg'],
    18: ['https://mp.weixin.qq.com/s/jNsrYckohD6E3FRBjwX-6Q', 'https://mp.weixin.qq.com/s/csdupVdwzzUJL9LzsAg-eA'],
    19: ['https://mp.weixin.qq.com/s/qZ0uhSgZh4Hs-M8rZN6SOA'],
    20: ['https://mp.weixin.qq.com/s/arBGWMUt7HV5nVdctPK0pw'],
    21: ['https://mp.weixin.qq.com/s/i38lFj2AXNFqB_gwq7IU0Q'],
    22: ['https://mp.weixin.qq.com/s/3O8F8RNmSoIe9TaSK_NEFw'],
    23: ['https://mp.weixin.qq.com/s/buoBR7qtCaoqkfW3JBSmIw'],
    24: ['https://mp.weixin.qq.com/s/qhDoX-Z97AvsXtIpspau-Q'],
    25: ['https://mp.weixin.qq.com/s/6OqoDwP2S7PF86B5P6CoaQ', 'https://mp.weixin.qq.com/s/Bkjes-7CyqKDg6NuNqLQ3w'],
    26: ['https://mp.weixin.qq.com/s/iNwRgpS32d-ZI8euvqu-4w', 'https://mp.weixin.qq.com/s/TmvVSnR2co9J8spA8TYeNg'],
    27: ['https://mp.weixin.qq.com/s/385QLKdsx5B_8JEyx-FKhw'],
    28: ['https://mp.weixin.qq.com/s/Ef2-kt9PAx18jCtXBIHmjg'],
    29: ['https://mp.weixin.qq.com/s/c4XO5gbqggH_RswGNlakqg'],
    30: ['https://mp.weixin.qq.com/s/wM6wGCo6rEkj3tuv9Es8vw'],
    31: ['https://mp.weixin.qq.com/s/FOwkeV77vK_TcvyOkm5SpQ'],
    32: ['https://mp.weixin.qq.com/s/fMT2froWluuyqqdT0IfrUw'],
    33: ['https://mp.weixin.qq.com/s/biecvCjkvZEVL3liPc797w'],
    34: ['https://mp.weixin.qq.com/s/_SjsIEo6-fWIN8CAvZl9ew'],
    35: ['https://mp.weixin.qq.com/s/WrW99gKP8LZvdfS7nSMBQQ'],
    36: ['https://mp.weixin.qq.com/s/CfYZ3SQ8ReSXQrxpJ0Sk1g'],
    37: ['https://mp.weixin.qq.com/s/oVHNm2Hdjc8haklCw7AoUw'],
    38: ['https://mp.weixin.qq.com/s/JtFtcW43J3eiJw1HOvFBZQ'],
    39: ['https://mp.weixin.qq.com/s/pOeJ9DfS7GRb0CPv8IeaSA'],
    40: ['https://mp.weixin.qq.com/s/EsNFzhPJD5rbReZ_vTMpXA'],
    41: ['https://mp.weixin.qq.com/s/mrrXwVctIo3JUb7CacjgLg'],
    42: ['https://mp.weixin.qq.com/s/0VMe3SDB5Isjbs1_i9_AXg'],
    43: ['https://mp.weixin.qq.com/s/b3qruTHZe7DponPQnJavhA'],
    44: ['https://mp.weixin.qq.com/s/DOIdd-Nb4HKXNGjrDYydig'],
    45: ['https://mp.weixin.qq.com/s/HrJ2bChy2tRWbchgkBSsRw', 'https://mp.weixin.qq.com/s/eBKOf-pov2NjGTrN7Qac-w'],
    46: ['https://mp.weixin.qq.com/s/wllwRdGNDGwtjqgQzh93UQ', 'https://mp.weixin.qq.com/s/3_XtC2ZvSVWFNGM5zNAp2Q'],
    47: ['https://mp.weixin.qq.com/s/6Z7-lJ0onyFY6fgS0vcp-Q', 'https://mp.weixin.qq.com/s/PGAKNV41r-0y09MJ9VkkYA'],
    48: ['https://mp.weixin.qq.com/s/zUR2BUmd-4FvZAqpXlCRiQ', 'https://mp.weixin.qq.com/s/u5hRn9quhozEY_yTHbVr2w'],
    49: ['https://mp.weixin.qq.com/s/v4TQm05VKN06PMF76i2raA'],
    50: ['https://mp.weixin.qq.com/s/Y-AddS4CU9alBZOVxKx0kA', 'https://mp.weixin.qq.com/s/3_XtC2ZvSVWFNGM5zNAp2Q'],
    51: ['https://mp.weixin.qq.com/s/8WYS6995Esx8EeU7vecQoQ'],
    52: ['https://mp.weixin.qq.com/s/RaevX9VMLKWX2OCg_WJJXQ'],
    53: ['https://mp.weixin.qq.com/s/G1Httwqaj6i0AKSoigTJOw'],
    54: ['https://mp.weixin.qq.com/s/XX6a4991CGwemTK-mKrwVw', 'https://mp.weixin.qq.com/s/P55afy2XaRQCFuJWWmo7Gg', 'https://mp.weixin.qq.com/s/bQdzNMCWER_ufa9lJdOB1g'],
    55: ['https://mp.weixin.qq.com/s/7a6gm6klVyBX3sfcXt8OJA', 'https://mp.weixin.qq.com/s/2h3XPmFX8GZ-SydWywhnAA'],
    56: ['https://mp.weixin.qq.com/s/kTQ0Enefwe5CzPUU0rMMQA', 'https://mp.weixin.qq.com/s/gvWhy2mBr9iFoai9HulpvA'],
    59: ['https://mp.weixin.qq.com/s/rervvwKkqC5cGkq5yBXNzg', 'https://mp.weixin.qq.com/s/HmJDMtwPQ2AGdxRAGsDVLw', 'https://mp.weixin.qq.com/s/aOA2dUsrx98UPLn5qG8okA'],
    60: ['https://mp.weixin.qq.com/s/PKg29jFz6Y9hPk956qN45w', 'https://mp.weixin.qq.com/s/2JgoyibLwIkWzYJX4f5jJg', 'https://mp.weixin.qq.com/s/3OH5w1LQ2YhaSUuKIv4HOQ'],
    61: ['https://mp.weixin.qq.com/s/Oeal_0vaWb8zKHIzs4r7WA', 'https://mp.weixin.qq.com/s/O1DzePwyqkMnETqU_AfqWA'],
    62: ['https://mp.weixin.qq.com/s/hKzvCA7qC8-Dw4IA7C-8GA', 'https://mp.weixin.qq.com/s/QZlIt4wjeGNMJkZYkKg39Q', 'https://mp.weixin.qq.com/s/sDU8LtunOuaZdAgqwS0Csg'],
    63: ['https://mp.weixin.qq.com/s/eq6SYlFNn4VKlOHhOpuVMA', 'https://mp.weixin.qq.com/s/Akodk-75sFI0npYvNMQPUw', 'https://mp.weixin.qq.com/s/ZnvWqNX0jfyBhyxCFYwuOg'],
    64: ['https://mp.weixin.qq.com/s/Ss21VIsC-Bzx0sWs38uvGQ'],
    65: ['https://mp.weixin.qq.com/s/O4o_OA-MsFqZfm8b4aYmBw', 'https://mp.weixin.qq.com/s/s9DhQEEgukvoFmRTErrLEw'],
    66: ['https://mp.weixin.qq.com/s/fI-ryXdo_ScVNORfCJfG6Q', 'https://mp.weixin.qq.com/s/xJmep5D02RUgpojiRlm4MA'],
    67: ['https://mp.weixin.qq.com/s/d_mFvoQX9LOB4AYKFs31fA', 'https://mp.weixin.qq.com/s/lBl6T67P8Hq6giOUwoR5GA'],
    68: ['https://mp.weixin.qq.com/s/heLWeJuvqF-elXy7h8V-mg', 'https://mp.weixin.qq.com/s/9_IDAj2GHoY9Wq3FYVAd-w'],
    69: ['https://mp.weixin.qq.com/s/vGA0bagROGC5IZYzIzz5kw'],
    70: ['https://mp.weixin.qq.com/s/A8aZyBXjZiQUCK8m3SPi3g', 'https://mp.weixin.qq.com/s/RMloKa_X4HTJi93_dLbbNg'],
    71: ['https://mp.weixin.qq.com/s/rZHUQlQR3WMcusKvvS4ZCQ', 'https://mp.weixin.qq.com/s/XVgm-FggklLA0VfGlGMDSA', 'https://mp.weixin.qq.com/s/4jmzJ6qb4C4lxYh69LHmnQ'],
    72: ['https://mp.weixin.qq.com/s/u9ZnB0pigl6zXw4GdC2lwg'],
    73: ['https://mp.weixin.qq.com/s/OczneO1gmoYBcTUCrj-Qag', 'https://mp.weixin.qq.com/s/clUZZWf18-3toNA6Eb5YQQ', 'https://mp.weixin.qq.com/s/QQzMGUhm0oa7JIiiAZ5pRA', 'https://mp.weixin.qq.com/s/FrQmgp8pjljpbsOwOkcIUQ', 'https://mp.weixin.qq.com/s/JvIh_2C2eF0dZaBHFO8nHg'],
    74: ['https://mp.weixin.qq.com/s/TNKJNfmdQU2nLGjUjNjvTg'],
    75: ['https://mp.weixin.qq.com/s/QGXs8hO97_3UcOR6LReJrA', 'https://mp.weixin.qq.com/s/AQvCNuVaOyhHqNtwLHw2Cw'],
    76: ['https://mp.weixin.qq.com/s/UuLz9QKQ4ZI6JUIV-eKmew'],
    77: ['https://mp.weixin.qq.com/s/ZcjgJK0ZpyNeBYoGjYEiow'],
    78: ['https://mp.weixin.qq.com/s/Q_BO-WXezFAhvTuhNTHAXA'],
    79: ['https://mp.weixin.qq.com/s/TN26tBD_rijAZtxeCbrO1A'],
    80: ['https://mp.weixin.qq.com/s/xvASTTF0gWKj9D-zVucZsg'],
    81: ['https://mp.weixin.qq.com/s/IyA3DxkMiMbcdoK1V1SUjg'],
    82: ['https://mp.weixin.qq.com/s/Vlr1cMvfNZ36qWppX3VLjw'],
    83: ['https://mp.weixin.qq.com/s/ChcqQtKJhUd7t1JjMJtq2g', 'https://mp.weixin.qq.com/s/rS2SAp2DNz9FblOHu3BaXA'],
    84: ['https://mp.weixin.qq.com/s/UyVMk2WajxyUHqYCBGA25A', 'https://mp.weixin.qq.com/s/IJ520FtkwBICLsVdSKurHg'],
    85: ['https://mp.weixin.qq.com/s/7HHokrYjupbmOlyCw8sWeQ'],
    86: ['https://mp.weixin.qq.com/s/9__Rs2mTSKRc91Tb8TYK8g'],
    87: ['https://mp.weixin.qq.com/s/uYfVzMnrlp9fhp4lJXPETw'],
    88: ['https://mp.weixin.qq.com/s/Ux65spqru517abvE1drnkQ'],
    89: ['https://mp.weixin.qq.com/s/g0iXF1hCOzObZfX5kOixwQ'],
    90: ['https://mp.weixin.qq.com/s/2mMZ0ZmL21D7Mqd_fClTmQ'],
    91: ['https://mp.weixin.qq.com/s/JN8TYWxinQX9rP6_R67k5g', 'https://mp.weixin.qq.com/s/sHo0jfQRGzcCVBW_lpRBaQ', 'https://mp.weixin.qq.com/s/gBj6_IZ3tQQV_gR9JyESKw', 'https://mp.weixin.qq.com/s/cqXQpQ-cw24xQDfdDNyadw'],
    92: ['https://mp.weixin.qq.com/s/P8_6ioayH8t-JVN0jXvkuw'],
    93: ['https://mp.weixin.qq.com/s/9aWEMAIIOas6RzJMd7gKYQ'],
    95: ['https://mp.weixin.qq.com/s/wEE7okmVntWh9FW1rTfzrQ'],
    96: ['https://mp.weixin.qq.com/s/TOn8UF2GOyjoM6ect89H1A'],
    97: ['https://mp.weixin.qq.com/s/9kXKgdawx4A1rQH9OsbtrQ', 'https://mp.weixin.qq.com/s/XR_yEZVDAXK58Z6sH_HKnA'],
    98: ['https://mp.weixin.qq.com/s/Gfs6PHsMABO-fR2YEfAndw', 'https://mp.weixin.qq.com/s/csqs7MJBef8z8H47s3v5lg'],
    99: ['https://mp.weixin.qq.com/s/DwO57xAIAPO4-ZjuoGYDkQ', 'https://mp.weixin.qq.com/s/7S7aGQcFSooVKJI7r1ukIw'],
    100: ['https://mp.weixin.qq.com/s/iDPaHcur_EWmwj2Eg5HKDw'],
    101: ['https://mp.weixin.qq.com/s/H4AD3VNAD8waF5u3_xPVew'],
    102: ['https://mp.weixin.qq.com/s/H6nOiZ_zitZjMIeA6FeaMQ', 'https://mp.weixin.qq.com/s/U200TImMMQB3u4HuWIUFxg'],
    103: ['https://mp.weixin.qq.com/s/JcZcyE5SQuMjkUSkPbUlMg'],
    104: ['https://mp.weixin.qq.com/s/XGICXJoIzVUTKUq2G2Ly8Q'],
    105: ['https://mp.weixin.qq.com/s/oFQiUPDVmE8_QsXDJbFFUA'],
    106: ['https://mp.weixin.qq.com/s/C9FMXeXdvfi3vyJQBG-UJg', 'https://mp.weixin.qq.com/s/cWviQVfSnj0ll6dOpVj6zg'],
    107: ['https://mp.weixin.qq.com/s/4-bhJ_35d8SZW4Yfoz4hXg', 'https://mp.weixin.qq.com/s/-LQY6iroI6qElSLodDJXNw', 'https://mp.weixin.qq.com/s/Rog3MoBE9pnfOfjYrjoTOw'],
    108: ['https://mp.weixin.qq.com/s/SivPY5sN3a2qxzNc7OysdQ', 'https://mp.weixin.qq.com/s/cKZwmIg8iJrsoNg80thvsA'],
    109: ['https://mp.weixin.qq.com/s/AkqH6dM8jposywBP7Zf_FQ'],
    110: ['https://mp.weixin.qq.com/s/cyrYaohaULFCWsvNzoWKuw', 'https://mp.weixin.qq.com/s/-vzEDNvE8sSbTRWEIswhpA', 'https://mp.weixin.qq.com/s/H-EasqIa4PbG7tQLMjovTw'],
    111: ['https://mp.weixin.qq.com/s/ieAdBYpFhTMUGpNq0GgF6A', 'https://mp.weixin.qq.com/s/dRkpZOy-sRCPmkX1Y7Z2Ug'],
    112: ['https://mp.weixin.qq.com/s/f-yfLxXx3M8xkvu4qNybvQ'],
    113: ['https://mp.weixin.qq.com/s/QDPCqWwLkiFosv7AHQzwPQ'],
    114: ['https://mp.weixin.qq.com/s/cLroIjtPnBvXh6x4WgRiDA'],
    115: ['https://mp.weixin.qq.com/s/l4mQQqprYWx2NJEeDVHW5Q'],
    116: ['https://mp.weixin.qq.com/s/Noo8O_phMcjkQcKYsuFDJA'],
    117: ['https://mp.weixin.qq.com/s/JLtd6UySQ3ocLct_W7NEqw'],
    118: ['https://mp.weixin.qq.com/s/8K8lFJq68KK2RBe9esn7eA', 'https://mp.weixin.qq.com/s/-gM9K1WfvkliVbIJ4TveWg'],
    119: ['https://mp.weixin.qq.com/s/U7N-4wkdcNnEiVkqvvBxAQ'],
    120: ['https://mp.weixin.qq.com/s/0OEXSg5Q2QW5IxbItlk9gA'],
    125: ['https://mp.weixin.qq.com/s/BYlC_iB-Da6m_7cgsokkyQ'],
    126: ['https://mp.weixin.qq.com/s/R3uxS0L8bs3KfAHH_nvJLw', 'https://mp.weixin.qq.com/s/E1w7EeITb6U5-WrEqxO1gQ'],
    127: ['https://mp.weixin.qq.com/s/MYkgyzISBkQ7WOJJw-F5VA', 'https://mp.weixin.qq.com/s/FQBlqBXYVYbc6Rw4-gkq8w'],
    128: ['https://mp.weixin.qq.com/s/i5mzyluSw3dSEOQQfWHjvQ'],
    129: ['https://mp.weixin.qq.com/s/yxvinOl31Q8MhmMXhLhIlA'],
    130: ['https://mp.weixin.qq.com/s/BqG5eZvqlqk3zMjdLMpNcQ', 'https://mp.weixin.qq.com/s/EsA8Cfr8pVtyUD-es0oqjQ'],
    131: ['https://mp.weixin.qq.com/s/0rIX8NvYiQgAMr5YvEcUOw'],
    133: ['https://mp.weixin.qq.com/s/CCbQibBP14zgavdtk7w3Fg'],
    134: ['https://mp.weixin.qq.com/s/eDohBKLnBudMASDjsT2tLg'],
    135: ['https://mp.weixin.qq.com/s/sLcJvjnptGbmbn1BZ0VDqA', 'https://mp.weixin.qq.com/s/M3hIYzIA3pnP-0GZmZ98bA'],
    136: ['https://mp.weixin.qq.com/s/UIPZYPPNpC-HU1D8VcZ85A', 'https://mp.weixin.qq.com/s/kqqU101v2HNGLirlVcpwAw'],
    137: ['https://mp.weixin.qq.com/s/JVrkLWRJqpuIuHYBhKFsZQ'],
    138: ['https://mp.weixin.qq.com/s/wuK_QtAOjMzIZwrAWiUqRg', 'https://mp.weixin.qq.com/s/YRSXcoxnttCk8Yr2YiH1zg'],
}
